import React from "react";
import { FONTS } from "../constants";
import { sanitizeHtml } from "../utils";

/* ========== COMPONENT RENDERER ========== */
const ANIM_STYLE = `
@keyframes tp-shimmer{0%{background-position:200% 0}100%{background-position:-200% 0}}
@keyframes tp-pulse{0%,100%{opacity:1}50%{opacity:.4}}
@keyframes tp-blink{0%,100%{opacity:1}50%{opacity:0}}
@keyframes tp-grow{from{transform:scaleY(0)}to{transform:scaleY(1)}}
@keyframes tp-fill{from{width:0}}
@keyframes tp-slidein{from{transform:translateY(8px);opacity:0}to{transform:translateY(0);opacity:1}}
@keyframes tp-ring{from{stroke-dasharray:0 238}}
@keyframes tp-draw{from{stroke-dashoffset:200}to{stroke-dashoffset:0}}
@keyframes tp-count{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}
@keyframes tp-bar-grow{from{height:0}}
@keyframes tp-gradient-shift{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}
@keyframes tp-typing{from{width:0}to{width:100%}}
@keyframes tp-cursor{0%,100%{border-color:currentColor}50%{border-color:transparent}}
`;

function C({type,v=0,p,editable,texts={},onText,font=0}){
  const f=FONTS[font]?.family||FONTS[0].family;
  const b={width:"100%",height:"100%",fontFamily:f,overflow:"hidden"};

  const T=({k,s,children})=>{
    const val=texts[k]!==undefined?texts[k]:children;
    const hasHtml=typeof val==="string"&&/<\w/.test(val);
    if(!editable)return hasHtml
      ?<span style={s} dangerouslySetInnerHTML={{__html:sanitizeHtml(val)}}/>
      :<span style={s}>{val}</span>;
    const ceProps={"data-text-key":k,contentEditable:true,suppressContentEditableWarning:true,
      onInput:e=>{onText?.(k,e.target.innerHTML)},
      onMouseDown:e=>e.stopPropagation(),
      onKeyDown:e=>{if(e.key==="Enter"){e.preventDefault();e.target.blur()}},
      style:{...s,outline:"none",cursor:"text",minWidth:8}};
    return hasHtml
      ?<span {...ceProps} dangerouslySetInnerHTML={{__html:sanitizeHtml(val)}}/>
      :<span {...ceProps}>{val}</span>;
  };

  const Img=({k,s,children})=>{
    const src=texts[k];
    const pick=()=>{if(!editable)return;const inp=document.createElement("input");inp.type="file";inp.accept="image/*";inp.onchange=ev=>{const file=ev.target.files[0];if(!file)return;const rd=new FileReader();rd.onload=r=>{onText?.(k,r.target.result)};rd.onerror=()=>{console.error("Failed to read image file")};rd.readAsDataURL(file)};inp.click()};
    const drop=e=>{e.preventDefault();e.stopPropagation();if(!editable)return;const file=(e.dataTransfer?.files||[])[0];if(!file||!file.type.startsWith("image/"))return;const rd=new FileReader();rd.onload=r=>{onText?.(k,r.target.result)};rd.onerror=()=>{console.error("Failed to read image file")};rd.readAsDataURL(file)};
    if(src)return <div style={{...s,overflow:"hidden",position:"relative"}} onClick={pick} onDragOver={e=>e.preventDefault()} onDrop={drop} onMouseDown={e=>e.stopPropagation()}><img src={src} style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}}/></div>;
    return <div style={s} onClick={pick} onDragOver={e=>e.preventDefault()} onDrop={drop} onMouseDown={e=>e.stopPropagation()}>{children}</div>;
  };

  /* ---- BUTTON ---- */
  if(type==="button"){
    if(v===0)return <div style={{...b,background:p.ac,borderRadius:10,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{color:"#fff",fontSize:13,fontWeight:500}}>Get started</T></div>;
    if(v===1)return <div style={{...b,background:"transparent",borderRadius:10,border:`1.5px solid ${p.ac}55`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{color:p.ac,fontSize:13,fontWeight:500}}>Learn more</T></div>;
    if(v===2)return <div style={{...b,background:"transparent",borderRadius:10,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{color:p.ac,fontSize:13,fontWeight:500}}>Learn more</T></div>;
    if(v===3)return <div style={{...b,background:p.ac,borderRadius:999,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{color:"#fff",fontSize:13,fontWeight:500}}>Get started</T></div>;
    if(v===4)return <div style={{...b,background:p.tx,borderRadius:4,display:"flex",alignItems:"center",justifyContent:"center",border:`2px solid ${p.tx}`}}><T k="label" s={{color:p.bg,fontSize:13,fontWeight:600,letterSpacing:"0.04em"}}>SUBMIT</T></div>;
    if(v===5)return <div style={{...b,background:`${p.ac}18`,backdropFilter:"blur(12px)",borderRadius:12,border:`1px solid ${p.ac}22`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{color:p.ac,fontSize:13,fontWeight:500}}>Get started</T></div>;
    return <div style={{...b,background:"#0a0a0c",borderRadius:2,border:`1px solid ${p.ac}44`,display:"flex",alignItems:"center",justifyContent:"center",gap:6}}><span style={{color:p.ac,fontSize:11,fontFamily:"'JetBrains Mono',monospace",opacity:.5,animation:"tp-blink 1.2s step-end infinite"}}>$</span><T k="label" s={{color:p.ac,fontSize:12,fontWeight:500,fontFamily:"'JetBrains Mono',monospace",letterSpacing:"0.03em"}}>EXECUTE</T></div>;
  }

  /* ---- CARD ---- */
  if(type==="card"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:14,boxShadow:`0 2px 12px ${p.tx}08, 0 0 0 1px ${p.bd}`,padding:20,display:"flex",flexDirection:"column",gap:8}}><Img k="icon" s={{width:36,height:36,borderRadius:10,background:p.su}}/><T k="title" s={{fontSize:14,fontWeight:600,color:p.tx}}>Card title</T><T k="desc" s={{fontSize:11,color:p.mu,lineHeight:1.5}}>A short description for this card component</T><div style={{marginTop:"auto",height:34,borderRadius:8,background:p.ac,opacity:.12,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{fontSize:11,color:p.ac,fontWeight:500}}>Action</T></div></div>;
    if(v===1)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:20,display:"flex",flexDirection:"column",gap:8}}><Img k="icon" s={{width:36,height:36,borderRadius:10,background:p.su}}/><T k="title" s={{fontSize:14,fontWeight:600,color:p.tx}}>Card title</T><T k="desc" s={{fontSize:11,color:p.mu,lineHeight:1.5}}>A short description for this card component</T><div style={{marginTop:"auto",height:34,borderRadius:8,border:`1.5px solid ${p.ac}33`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{fontSize:11,color:p.ac,fontWeight:500}}>Action</T></div></div>;
    if(v===2)return <div style={{...b,background:p.su,borderRadius:16,padding:22,display:"flex",flexDirection:"column",gap:8}}><Img k="icon" s={{width:40,height:40,borderRadius:999,background:p.ac+"18",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{width:18,height:18,borderRadius:999,background:p.ac,opacity:.35}}/></Img><T k="title" s={{fontSize:14,fontWeight:600,color:p.tx}}>Card title</T><T k="desc" s={{fontSize:11,color:p.mu,lineHeight:1.5}}>A short description for this card</T><div style={{marginTop:"auto",height:36,borderRadius:10,background:p.ac,opacity:.1,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{fontSize:11,color:p.ac,fontWeight:500}}>Action</T></div></div>;
    if(v===3)return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,overflow:"hidden",display:"flex",flexDirection:"column"}}><Img k="media" s={{height:"42%",background:p.su}}/><div style={{padding:16,display:"flex",flexDirection:"column",gap:6,flex:1}}><T k="title" s={{fontSize:14,fontWeight:600,color:p.tx}}>Card title</T><T k="desc" s={{fontSize:11,color:p.mu,lineHeight:1.5}}>Description text goes here</T></div></div>;
    if(v===4)return <div style={{...b,background:p.card,borderRadius:12,padding:20,display:"flex",flexDirection:"column",gap:8}}><T k="title" s={{fontSize:14,fontWeight:600,color:p.tx}}>Card title</T><T k="desc" s={{fontSize:11,color:p.mu,lineHeight:1.5}}>A minimal card layout with just text content for clean designs</T></div>;
    if(v===5)return <div style={{...b,background:`${p.card}88`,backdropFilter:"blur(16px)",borderRadius:16,border:`1px solid ${p.ac}15`,padding:20,display:"flex",flexDirection:"column",gap:8}}><Img k="icon" s={{width:36,height:36,borderRadius:10,background:`${p.ac}12`}}/><T k="title" s={{fontSize:14,fontWeight:600,color:p.tx}}>Card title</T><T k="desc" s={{fontSize:11,color:p.mu,lineHeight:1.5}}>A short description for this card</T><div style={{marginTop:"auto",height:34,borderRadius:10,background:`${p.ac}10`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{fontSize:11,color:p.ac,fontWeight:500}}>Action</T></div></div>;
    if(v===6)return <div style={{...b,background:p.card,borderRadius:4,border:`3px solid ${p.tx}`,boxShadow:`4px 4px 0 ${p.tx}`,padding:18,display:"flex",flexDirection:"column",gap:8}}><Img k="icon" s={{width:36,height:36,borderRadius:4,background:p.ac,opacity:.2}}/><T k="title" s={{fontSize:14,fontWeight:600,color:p.tx}}>Card title</T><T k="desc" s={{fontSize:11,color:p.mu,lineHeight:1.5}}>Description for this card</T><div style={{marginTop:"auto",height:34,borderRadius:4,background:p.tx,opacity:.08,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{fontSize:11,color:p.tx,fontWeight:500,opacity:.5}}>Action</T></div></div>;
    return <div style={{...b,background:"#0c0c0e",borderRadius:2,border:`1px solid ${p.ac}30`,padding:16,display:"flex",flexDirection:"column",gap:8,fontFamily:"'JetBrains Mono',monospace"}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:2}}><div style={{width:7,height:7,borderRadius:999,background:p.ac,opacity:.6,animation:"tp-pulse 2s ease infinite"}}/><T k="title" s={{fontSize:11,fontWeight:600,color:p.ac,textTransform:"uppercase",letterSpacing:"0.06em"}}>SYS.MODULE</T></div><T k="desc" s={{fontSize:10,color:"#888",lineHeight:1.6}}>Protocol active — monitoring upstream signals for anomaly detection</T><div style={{marginTop:"auto",display:"flex",gap:8}}><div style={{flex:1,height:28,borderRadius:2,border:`1px solid ${p.ac}25`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{fontSize:9,color:p.ac,fontWeight:500,letterSpacing:"0.05em"}}>INSPECT</T></div><div style={{flex:1,height:28,borderRadius:2,background:p.ac+"18",display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta2" s={{fontSize:9,color:p.ac,fontWeight:500,letterSpacing:"0.05em"}}>DEPLOY</T></div></div></div>;
  }

  /* ---- CARD-SM ---- */
  if(type==="card-sm"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,padding:14,display:"flex",flexDirection:"column",gap:6}}><Img k="icon" s={{width:28,height:28,borderRadius:8,background:p.su}}/><T k="title" s={{fontSize:12,fontWeight:600,color:p.tx}}>Small card</T><T k="desc" s={{fontSize:10,color:p.mu}}>Short description</T></div>;
    if(v===1)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:14,display:"flex",gap:12,alignItems:"center"}}><Img k="icon" s={{width:44,height:44,borderRadius:10,background:p.su,flexShrink:0}}/><div style={{flex:1,display:"flex",flexDirection:"column",gap:4}}><T k="title" s={{fontSize:12,fontWeight:600,color:p.tx}}>Small card</T><T k="desc" s={{fontSize:10,color:p.mu}}>Short description</T></div></div>;
    return <div style={{...b,background:p.su,borderRadius:16,padding:14,display:"flex",flexDirection:"column",gap:6}}><Img k="icon" s={{width:30,height:30,borderRadius:999,background:p.ac+"1A"}}/><T k="title" s={{fontSize:12,fontWeight:600,color:p.tx}}>Small card</T><T k="desc" s={{fontSize:10,color:p.mu}}>Short description</T></div>;
  }

  /* ---- HERO ---- */
  if(type==="hero"){
    if(v===0)return <div style={{...b,background:`linear-gradient(135deg,${p.ac}12,${p.ac2}12)`,borderRadius:16,border:`1px solid ${p.bd}`,padding:32,display:"flex",flexDirection:"column",justifyContent:"center",gap:8}}><T k="title" s={{fontSize:20,fontWeight:700,color:p.tx,letterSpacing:"-0.02em"}}>Hero headline here</T><T k="sub" s={{fontSize:12,color:p.mu,lineHeight:1.5}}>Supporting text for the hero section</T><div style={{display:"flex",gap:10,marginTop:8}}><div style={{height:38,width:110,borderRadius:9,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:"#fff",fontSize:12,fontWeight:500}}>Get started</T></div><div style={{height:38,width:95,borderRadius:9,border:`1.5px solid ${p.ac}44`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta2" s={{color:p.ac,fontSize:12,fontWeight:500}}>Learn more</T></div></div></div>;
    if(v===1)return <div style={{...b,background:p.card,borderRadius:4,border:`1px solid ${p.bd}`,padding:"36px 32px",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:8,textAlign:"center"}}><T k="title" s={{fontSize:20,fontWeight:700,color:p.tx}}>Hero headline</T><T k="sub" s={{fontSize:12,color:p.mu}}>Supporting text for this section</T><div style={{height:36,width:120,borderRadius:3,background:p.tx,marginTop:12,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:p.bg,fontSize:12,fontWeight:500}}>Start now</T></div></div>;
    if(v===2)return <div style={{...b,background:p.ac,borderRadius:20,padding:36,display:"flex",flexDirection:"column",justifyContent:"center",gap:8}}><T k="title" s={{fontSize:20,fontWeight:700,color:"#fff"}}>Hero headline here</T><T k="sub" s={{fontSize:12,color:"#fff",opacity:.65,lineHeight:1.5}}>Supporting text for the hero section</T><div style={{height:38,width:115,borderRadius:999,background:"#fff",marginTop:10,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:p.ac,fontSize:12,fontWeight:600}}>Get started</T></div></div>;
    return <div style={{...b,background:"#08080a",borderRadius:2,border:`1px solid ${p.ac}20`,padding:32,display:"flex",flexDirection:"column",justifyContent:"center",gap:10,fontFamily:"'JetBrains Mono',monospace"}}><div style={{fontSize:9,color:p.ac,opacity:.5,letterSpacing:"0.1em"}}>// INIT SEQUENCE<span style={{borderRight:"2px solid currentColor",marginLeft:2,animation:"tp-blink 1s step-end infinite"}}>&nbsp;</span></div><T k="title" s={{fontSize:22,fontWeight:700,color:"#f0f0f0",letterSpacing:"-0.02em",fontFamily:"'Space Grotesk',system-ui"}}>SIGNAL CAPTURE</T><T k="sub" s={{fontSize:11,color:"#666",lineHeight:1.6}}>Real-time telemetry · Protocol v2.4 · Uptime 99.97%</T><div style={{display:"flex",gap:10,marginTop:8}}><div style={{height:36,width:120,borderRadius:2,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:"#000",fontSize:11,fontWeight:600,letterSpacing:"0.04em"}}>LAUNCH →</T></div><div style={{height:36,width:100,borderRadius:2,border:`1px solid #333`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta2" s={{color:"#888",fontSize:11,fontWeight:500}}>DOCS</T></div></div></div>;
  }

  /* ---- NAVBAR ---- */
  if(type==="navbar"){
    const dl=["Home","Features","Pricing"];
    if(v===0)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:"0 18px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:16}}><Img k="logo" s={{width:20,height:20,borderRadius:6,background:p.ac,opacity:.6}}/>{dl.map((t,i)=><T key={i} k={`link${i}`} s={{fontSize:12,color:i===0?p.tx:p.mu,fontWeight:i===0?500:400}}>{t}</T>)}</div><div style={{height:30,width:74,borderRadius:8,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:"#fff",fontSize:11,fontWeight:500}}>Sign up</T></div></div>;
    if(v===1)return <div style={{...b,borderBottom:`1.5px solid ${p.bd}`,padding:"0 18px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:20}}><T k="brand" s={{fontSize:14,fontWeight:600,color:p.tx,letterSpacing:"-0.02em"}}>Brand</T>{dl.map((t,i)=><T key={i} k={`link${i}`} s={{fontSize:12,color:p.mu}}>{t}</T>)}</div><div style={{height:30,width:70,borderRadius:4,border:`1.5px solid ${p.tx}`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:p.tx,fontSize:11,fontWeight:500}}>Log in</T></div></div>;
    if(v===2)return <div style={{...b,background:p.su,borderRadius:999,padding:"0 5px 0 18px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:14}}><Img k="logo" s={{width:18,height:18,borderRadius:999,background:p.ac,opacity:.5}}/>{dl.map((t,i)=><T key={i} k={`link${i}`} s={{fontSize:12,color:i===0?p.tx:p.mu,fontWeight:i===0?500:400}}>{t}</T>)}</div><div style={{height:34,width:78,borderRadius:999,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:"#fff",fontSize:11,fontWeight:500}}>Contact</T></div></div>;
    if(v===3)return <div style={{...b,background:`${p.card}66`,backdropFilter:"blur(16px)",borderRadius:14,border:`1px solid ${p.ac}12`,padding:"0 18px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:16}}><Img k="logo" s={{width:20,height:20,borderRadius:6,background:p.ac,opacity:.4}}/>{dl.map((t,i)=><T key={i} k={`link${i}`} s={{fontSize:12,color:i===0?p.tx:p.mu+"cc",fontWeight:i===0?500:400}}>{t}</T>)}</div><div style={{height:30,width:74,borderRadius:8,background:`${p.ac}18`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:p.ac,fontSize:11,fontWeight:500}}>Sign up</T></div></div>;
    return <div style={{...b,background:"#0a0a0c",borderRadius:0,borderBottom:`1px solid ${p.ac}20`,padding:"0 18px",display:"flex",alignItems:"center",justifyContent:"space-between",fontFamily:"'JetBrains Mono',monospace"}}><div style={{display:"flex",alignItems:"center",gap:16}}><T k="brand" s={{fontSize:11,fontWeight:600,color:p.ac,letterSpacing:"0.06em"}}>SYS.ID</T>{["HOME","DROPS","TERMINAL"].map((t,i)=><T key={i} k={`link${i}`} s={{fontSize:10,color:i===0?"#ccc":"#555",fontWeight:400,letterSpacing:"0.04em"}}>{t}</T>)}</div><div style={{height:28,width:28,borderRadius:2,border:`1px solid ${p.ac}30`,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:10,color:p.ac,opacity:.6,animation:"tp-pulse 2.5s ease infinite"}}>⌘</span></div></div>;
  }

  /* ---- TABS ---- */
  if(type==="tabs"){
    const dt=["Overview","Analytics","Reports"];
    if(v===0)return <div style={{...b,background:p.su,borderRadius:10,padding:3,display:"flex",gap:2,alignItems:"center"}}>{dt.map((t,i)=><div key={i} style={{flex:1,height:"calc(100% - 2px)",borderRadius:7,display:"flex",alignItems:"center",justifyContent:"center",background:i===0?p.card:"transparent",boxShadow:i===0?"0 1px 3px rgba(0,0,0,0.04)":"none"}}><T k={`tab${i}`} s={{fontSize:12,fontWeight:i===0?500:400,color:i===0?p.tx:p.mu}}>{t}</T></div>)}</div>;
    if(v===1)return <div style={{...b,borderBottom:`2px solid ${p.bd}`,display:"flex",gap:24,alignItems:"stretch",padding:"0 4px"}}>{dt.map((t,i)=><div key={i} style={{display:"flex",alignItems:"center",borderBottom:i===0?`2px solid ${p.ac}`:"2px solid transparent",marginBottom:-2}}><T k={`tab${i}`} s={{fontSize:12,fontWeight:i===0?500:400,color:i===0?p.ac:p.mu}}>{t}</T></div>)}</div>;
    return <div style={{...b,display:"flex",gap:6,alignItems:"center"}}>{dt.map((t,i)=><div key={i} style={{padding:"6px 14px",borderRadius:999,background:i===0?p.ac+"14":"transparent"}}><T k={`tab${i}`} s={{fontSize:12,fontWeight:i===0?500:400,color:i===0?p.ac:p.mu}}>{t}</T></div>)}</div>;
  }

  /* ---- HEADING ---- */
  if(type==="heading"){
    if(v===0)return <div style={{...b,display:"flex",alignItems:"flex-end"}}><T k="title" s={{fontSize:22,fontWeight:600,color:p.tx,letterSpacing:"-0.02em"}}>Page heading</T></div>;
    if(v===1)return <div style={{...b,display:"flex",alignItems:"flex-end",gap:10}}><div style={{width:4,height:24,borderRadius:2,background:p.ac}}/><T k="title" s={{fontSize:20,fontWeight:600,color:p.tx}}>Page heading</T></div>;
    return <div style={{...b,display:"flex",flexDirection:"column",justifyContent:"flex-end",gap:3}}><T k="over" s={{fontSize:10,fontWeight:600,color:p.ac,textTransform:"uppercase",letterSpacing:"0.1em"}}>Section</T><T k="title" s={{fontSize:20,fontWeight:500,color:p.tx}}>Page heading</T></div>;
  }

  /* ---- STAT-CARD ---- */
  if(type==="stat-card"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:14,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><T k="label" s={{fontSize:10,color:p.mu,fontWeight:500,textTransform:"uppercase",letterSpacing:"0.05em"}}>Revenue</T><T k="value" s={{fontSize:26,fontWeight:600,color:p.tx,letterSpacing:"-0.02em"}}>$48.2k</T><T k="delta" s={{fontSize:11,color:"#4CAF50",fontWeight:500}}>+12.5%</T></div>;
    if(v===1)return <div style={{...b,background:p.su,borderRadius:14,padding:14,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><T k="label" s={{fontSize:10,color:p.mu,fontWeight:500}}>Revenue</T><Img k="icon" s={{width:28,height:28,borderRadius:999,background:p.ac+"14",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:12,color:p.ac}}>$</span></Img></div><T k="value" s={{fontSize:24,fontWeight:600,color:p.tx,animation:"tp-count .5s ease-out"}}>$48.2k</T><div style={{height:4,borderRadius:2,background:p.ac+"1A"}}><div style={{width:"68%",height:"100%",borderRadius:2,background:p.ac,opacity:.5,animation:"tp-fill .8s ease-out forwards"}}/></div></div>;
    if(v===2)return <div style={{...b,background:p.card,borderRadius:4,borderLeft:`3px solid ${p.ac}`,padding:14,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><T k="label" s={{fontSize:10,color:p.mu,fontWeight:500}}>REVENUE</T><T k="value" s={{fontSize:28,fontWeight:600,color:p.tx}}>$48.2k</T><T k="delta" s={{fontSize:11,color:"#4CAF50",fontWeight:500}}>+12.5% vs prev</T></div>;
    if(v===3)return <div style={{...b,background:p.ac,borderRadius:14,padding:14,display:"flex",flexDirection:"column",justifyContent:"space-between"}}><T k="label" s={{fontSize:10,color:"#ffffff88",fontWeight:500}}>Revenue</T><T k="value" s={{fontSize:26,fontWeight:600,color:"#fff"}}>$48.2k</T><T k="delta" s={{fontSize:11,color:"#ffffff99"}}>+12.5%</T></div>;
    return <div style={{...b,background:"#0c0c0e",borderRadius:2,border:`1px solid ${p.ac}25`,padding:14,display:"flex",flexDirection:"column",justifyContent:"space-between",fontFamily:"'JetBrains Mono',monospace"}}><div style={{display:"flex",alignItems:"center",gap:4}}><div style={{width:5,height:5,borderRadius:999,background:p.ac,opacity:.5,animation:"tp-pulse 2s ease infinite"}}/><T k="label" s={{fontSize:9,color:"#666",fontWeight:500,textTransform:"uppercase",letterSpacing:"0.08em"}}>UPLINK</T></div><T k="value" s={{fontSize:24,fontWeight:600,color:p.ac,letterSpacing:"-0.02em"}}>99.97%</T><div style={{display:"flex",alignItems:"center",gap:4}}><span style={{fontSize:9,color:"#4CAF50"}}>▲</span><T k="delta" s={{fontSize:10,color:"#4CAF50"}}>+0.02%</T></div></div>;
  }

  /* ---- IMAGE-PLACEHOLDER ---- */
  if(type==="image-placeholder"){
    const src=texts.src;
    const upload=()=>{if(!editable)return;const inp=document.createElement("input");inp.type="file";inp.accept="image/*";inp.onchange=ev=>{const file=ev.target.files[0];if(!file)return;const rd=new FileReader();rd.onload=r=>{onText?.("src",r.target.result)};rd.onerror=()=>{console.error("Failed to read image file")};rd.readAsDataURL(file)};inp.click()};
    const ico=<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke={v===1?p.ac:p.mu} strokeWidth="1.5" strokeLinecap="round" opacity={v===1?.45:.2}><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg>;
    if(src)return <div style={{...b,borderRadius:12,overflow:"hidden",cursor:editable?"pointer":"default",position:"relative"}} onClick={upload}><img src={src} style={{width:"100%",height:"100%",objectFit:"cover"}}/>{editable&&<div style={{position:"absolute",inset:0,background:"rgba(0,0,0,.3)",display:"flex",alignItems:"center",justifyContent:"center",opacity:0,transition:"opacity .15s"}} onMouseEnter={e=>e.currentTarget.style.opacity=1} onMouseLeave={e=>e.currentTarget.style.opacity=0}><span style={{color:"#fff",fontSize:11,fontWeight:500}}>Replace image</span></div>}</div>;
    const placeholder=(st)=><div style={{...b,...st,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:6,cursor:editable?"pointer":"default"}} onClick={upload}>{ico}{editable&&<span style={{fontSize:10,color:p.mu,opacity:.4}}>Click to upload</span>}</div>;
    if(v===0)return placeholder({background:p.su,borderRadius:12,border:`1px solid ${p.bd}`});
    if(v===1)return placeholder({background:`linear-gradient(135deg,${p.ac}18,${p.ac2}18)`,borderRadius:16});
    return placeholder({background:p.su,borderRadius:4,border:`1.5px dashed ${p.mu}28`});
  }

  /* ---- AVATAR-ROW ---- */
  if(type==="avatar-row"){
    const rd=v===2?8:999, sz=v===1?26:v===2?34:30, ol=v===1?-5:-8;
    const labels=["A","B","C","+"];
    const bgs=[p.ac+"40",p.ac2+"40",p.mu+"28",p.ac+"22"];
    return <div style={{...b,display:"flex",alignItems:"center"}}>{[0,1,2,3].map(i=><Img key={i} k={`av${i}`} s={{width:sz,height:sz,borderRadius:rd,background:bgs[i],border:`2px solid ${p.bg}`,marginLeft:i>0?ol:0,display:"flex",alignItems:"center",justifyContent:"center",fontSize:v===2?11:10,fontWeight:500,color:p.mu}}>{labels[i]}</Img>)}</div>;
  }

  /* ---- LIST-ITEM ---- */
  if(type==="list-item"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:"0 14px",display:"flex",alignItems:"center",gap:12}}><Img k="icon" s={{width:36,height:36,borderRadius:10,background:p.su,flexShrink:0}}/><div style={{flex:1,display:"flex",flexDirection:"column",gap:2}}><T k="title" s={{fontSize:12,fontWeight:600,color:p.tx}}>List item title</T><T k="desc" s={{fontSize:10,color:p.mu}}>Description text</T></div><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={p.mu} strokeWidth="2" opacity=".2"><path d="M9 18l6-6-6-6"/></svg></div>;
    if(v===1)return <div style={{...b,borderBottom:`1px solid ${p.bd}`,padding:"0 4px",display:"flex",alignItems:"center",gap:12}}><Img k="icon" s={{width:32,height:32,borderRadius:999,background:p.ac+"15",flexShrink:0}}/><div style={{flex:1,display:"flex",flexDirection:"column",gap:2}}><T k="title" s={{fontSize:12,fontWeight:500,color:p.tx}}>List item title</T><T k="desc" s={{fontSize:10,color:p.mu}}>Description text</T></div></div>;
    return <div style={{...b,background:p.su,borderRadius:14,padding:"0 14px",display:"flex",alignItems:"center",gap:12}}><Img k="icon" s={{width:38,height:38,borderRadius:10,background:p.ac+"12",flexShrink:0}}/><div style={{flex:1,display:"flex",flexDirection:"column",gap:2}}><T k="title" s={{fontSize:12,fontWeight:600,color:p.tx}}>List item title</T><T k="desc" s={{fontSize:10,color:p.mu}}>Description text</T></div></div>;
  }

  /* ---- INPUT ---- */
  if(type==="input"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:10,border:`1.5px solid ${p.bd}`,padding:"0 14px",display:"flex",alignItems:"center"}}><T k="ph" s={{fontSize:13,color:p.mu,opacity:.45}}>Enter your email...</T></div>;
    if(v===1)return <div style={{...b,display:"flex",flexDirection:"column",gap:5,justifyContent:"flex-end"}}><T k="label" s={{fontSize:10,fontWeight:500,color:p.mu}}>Email</T><div style={{height:34,borderRadius:5,border:`1.5px solid ${p.bd}`,padding:"0 10px",display:"flex",alignItems:"center"}}><T k="ph" s={{fontSize:13,color:p.mu,opacity:.4}}>you@example.com</T></div></div>;
    return <div style={{...b,background:p.su,borderRadius:10,padding:"0 14px",display:"flex",alignItems:"center"}}><T k="ph" s={{fontSize:13,color:p.mu,opacity:.4}}>Enter your email...</T></div>;
  }

  /* ---- SEARCH ---- */
  if(type==="search"){
    const ico=<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={p.mu} strokeWidth="2" strokeLinecap="round" opacity=".3"><circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/></svg>;
    if(v===0)return <div style={{...b,background:p.card,borderRadius:10,border:`1.5px solid ${p.bd}`,padding:"0 12px",display:"flex",alignItems:"center",gap:8}}>{ico}<T k="ph" s={{fontSize:13,color:p.mu,opacity:.4}}>Search...</T></div>;
    if(v===1)return <div style={{...b,background:p.su,borderRadius:999,padding:"0 14px",display:"flex",alignItems:"center",gap:8}}>{ico}<T k="ph" s={{fontSize:13,color:p.mu,opacity:.4}}>Search...</T><span style={{marginLeft:"auto",fontSize:9,color:p.mu,opacity:.25,border:`1px solid ${p.bd}`,borderRadius:4,padding:"2px 6px"}}>Cmd+K</span></div>;
    return <div style={{...b,background:p.card,borderRadius:0,borderBottom:`2px solid ${p.ac}30`,padding:"0 8px",display:"flex",alignItems:"center",gap:8}}>{ico}<T k="ph" s={{fontSize:13,color:p.mu,opacity:.4}}>Search...</T></div>;
  }

  /* ---- TOGGLE ---- */
  if(type==="toggle"){
    if(v===0)return <div style={{...b,background:p.ac,borderRadius:999,padding:3,display:"flex",alignItems:"center",justifyContent:"flex-end",transition:"background .3s"}}><div style={{width:20,height:20,borderRadius:999,background:"#fff",boxShadow:"0 1px 3px rgba(0,0,0,.1)",transition:"transform .3s cubic-bezier(.4,.2,.2,1)"}}/></div>;
    return <div style={{...b,background:p.ac+"2A",borderRadius:6,padding:3,display:"flex",alignItems:"center",justifyContent:"flex-end",transition:"background .3s"}}><div style={{width:20,height:20,borderRadius:4,background:p.ac,transition:"transform .3s cubic-bezier(.4,.2,.2,1)"}}/></div>;
  }

  /* ---- BADGE ---- */
  if(type==="badge"){
    if(v===0)return <div style={{...b,background:p.ac+"14",borderRadius:999,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{fontSize:11,fontWeight:600,color:p.ac}}>New</T></div>;
    if(v===1)return <div style={{...b,background:p.ac,borderRadius:6,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{fontSize:11,fontWeight:600,color:"#fff"}}>New</T></div>;
    if(v===2)return <div style={{...b,border:`1.5px solid ${p.ac}44`,borderRadius:999,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{fontSize:11,fontWeight:500,color:p.ac}}>New</T></div>;
    if(v===3)return <div style={{...b,background:`${p.ac}12`,backdropFilter:"blur(8px)",borderRadius:999,border:`1px solid ${p.ac}18`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{fontSize:11,fontWeight:500,color:p.ac}}>New</T></div>;
    return <div style={{...b,background:p.ac,borderRadius:4,border:`2px solid ${p.tx}`,boxShadow:`2px 2px 0 ${p.tx}`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="label" s={{fontSize:11,fontWeight:700,color:"#fff"}}>New</T></div>;
  }

  /* ---- TOAST ---- */
  if(type==="toast"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:"0 14px",display:"flex",alignItems:"center",gap:10,boxShadow:`0 4px 20px ${p.tx}08`,animation:"tp-slidein .4s ease-out"}}><div style={{width:20,height:20,borderRadius:999,background:"#4CAF5018"}}/><T k="label" s={{fontSize:12,color:p.tx,fontWeight:500}}>Changes saved</T></div>;
    if(v===1)return <div style={{...b,background:p.tx,borderRadius:8,padding:"0 14px",display:"flex",alignItems:"center",gap:10,animation:"tp-slidein .4s ease-out"}}><T k="label" s={{fontSize:12,color:p.bg,fontWeight:500}}>Changes saved</T><T k="action" s={{marginLeft:"auto",fontSize:11,color:p.bg,opacity:.45}}>Undo</T></div>;
    if(v===2)return <div style={{...b,background:p.card,borderRadius:4,borderLeft:`3px solid #4CAF50`,padding:"0 14px",display:"flex",alignItems:"center",boxShadow:`0 2px 10px ${p.tx}06`,animation:"tp-slidein .4s ease-out"}}><T k="label" s={{fontSize:12,color:p.tx,fontWeight:500}}>Changes saved</T></div>;
    return <div style={{...b,background:`${p.card}88`,backdropFilter:"blur(16px)",borderRadius:14,border:`1px solid ${p.ac}12`,padding:"0 14px",display:"flex",alignItems:"center",gap:10,boxShadow:`0 8px 32px ${p.tx}08`,animation:"tp-slidein .4s ease-out"}}><div style={{width:20,height:20,borderRadius:999,background:"#4CAF5018"}}/><T k="label" s={{fontSize:12,color:p.tx,fontWeight:500}}>Changes saved</T></div>;
  }

  /* ---- PROGRESS ---- */
  if(type==="progress"){
    const rd=[999,4,0];
    return <div style={{...b,background:p.su,borderRadius:rd[v],overflow:"hidden"}}><div style={{width:"68%",height:"100%",background:v===1?`linear-gradient(90deg,${p.ac},${p.ac2})`:p.ac,borderRadius:rd[v],animation:"tp-fill .8s ease-out forwards"}}/></div>;
  }

  /* ---- MODAL ---- */
  if(type==="modal"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:16,border:`1px solid ${p.bd}`,boxShadow:`0 16px 48px ${p.tx}12`,padding:20,display:"flex",flexDirection:"column",gap:12}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><T k="title" s={{fontSize:15,fontWeight:600,color:p.tx}}>Confirm action</T><div style={{width:20,height:20,borderRadius:6,background:p.su,display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:12,color:p.mu,lineHeight:1}}>×</span></div></div><T k="body" s={{flex:1,fontSize:11,color:p.mu,lineHeight:1.5}}>Are you sure you want to proceed? This action will apply your changes.</T><div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><div style={{height:32,width:70,borderRadius:8,border:`1px solid ${p.bd}`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cancel" s={{fontSize:11,color:p.mu,fontWeight:500}}>Cancel</T></div><div style={{height:32,width:70,borderRadius:8,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="confirm" s={{fontSize:11,color:"#fff",fontWeight:500}}>Confirm</T></div></div></div>;
    if(v===1)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:24,display:"flex",flexDirection:"column",gap:12,alignItems:"center",textAlign:"center"}}><Img k="icon" s={{width:40,height:40,borderRadius:999,background:p.ac+"14",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:18,color:p.ac}}>?</span></Img><T k="title" s={{fontSize:15,fontWeight:600,color:p.tx}}>Are you sure?</T><T k="body" s={{fontSize:11,color:p.mu,lineHeight:1.5}}>This cannot be undone.</T><div style={{display:"flex",gap:8}}><div style={{height:32,width:80,borderRadius:8,border:`1px solid ${p.bd}`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cancel" s={{fontSize:11,color:p.mu}}>Cancel</T></div><div style={{height:32,width:80,borderRadius:8,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="confirm" s={{fontSize:11,color:"#fff",fontWeight:500}}>Confirm</T></div></div></div>;
    return <div style={{...b,background:p.card,borderRadius:"16px 16px 0 0",borderTop:`1px solid ${p.bd}`,boxShadow:`0 -8px 32px ${p.tx}08`,padding:20,display:"flex",flexDirection:"column",gap:10,animation:"tp-slidein .3s ease-out"}}><div style={{width:36,height:4,borderRadius:2,background:p.mu+"30",alignSelf:"center",marginBottom:4}}/><T k="title" s={{fontSize:15,fontWeight:600,color:p.tx}}>Select option</T><T k="body" s={{flex:1,fontSize:11,color:p.mu,lineHeight:1.5}}>Choose from the options below to continue.</T><div style={{height:36,borderRadius:10,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="confirm" s={{fontSize:12,color:"#fff",fontWeight:500}}>Continue</T></div></div>;
  }

  /* ---- SIDEBAR ---- */
  if(type==="sidebar"){
    const items=["Dashboard","Analytics","Settings","Users"];
    const Item=({t,k,active,iconOnly})=><div style={{padding:iconOnly?"8px":"7px 12px",borderRadius:8,background:active?p.ac+"14":"transparent",display:"flex",alignItems:"center",gap:10}}><div style={{width:16,height:16,borderRadius:4,background:active?p.ac+"40":p.mu+"20",flexShrink:0}}/>{!iconOnly&&<T k={k} s={{fontSize:12,color:active?p.ac:p.mu,fontWeight:active?500:400}}>{t}</T>}</div>;
    if(v===0)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:12,display:"flex",flexDirection:"column",gap:2}}><T k="brand" s={{fontSize:13,fontWeight:600,color:p.tx,padding:"2px 12px 10px"}}>Brand</T>{items.map((t,i)=><Item key={i} t={t} k={`nav${i}`} active={i===0}/>)}<div style={{marginTop:"auto",height:1,background:p.bd}}/><Item t="Log out" k="logout" active={false}/></div>;
    if(v===1)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:8,display:"flex",flexDirection:"column",gap:4,alignItems:"center",width:"100%"}}><Img k="logo" s={{width:24,height:24,borderRadius:8,background:p.ac+"20",marginBottom:8}}/>{items.map((t,i)=><Item key={i} t={t} k={`nav${i}`} active={i===0} iconOnly/>)}</div>;
    if(v===2)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:12,display:"flex",flexDirection:"column",gap:2}}><T k="brand" s={{fontSize:13,fontWeight:600,color:p.tx,padding:"2px 12px 8px"}}>Brand</T><T k="section1" s={{fontSize:9,color:p.mu,fontWeight:600,textTransform:"uppercase",letterSpacing:"0.08em",padding:"6px 12px 2px"}}>Main</T>{items.slice(0,2).map((t,i)=><Item key={i} t={t} k={`nav${i}`} active={i===0}/>)}<T k="section2" s={{fontSize:9,color:p.mu,fontWeight:600,textTransform:"uppercase",letterSpacing:"0.08em",padding:"10px 12px 2px"}}>System</T>{items.slice(2).map((t,i)=><Item key={i+2} t={t} k={`nav${i+2}`} active={false}/>)}</div>;
    return <div style={{...b,background:`${p.card}55`,backdropFilter:"blur(20px)",borderRadius:16,border:`1px solid ${p.ac}12`,padding:12,display:"flex",flexDirection:"column",gap:2}}><T k="brand" s={{fontSize:13,fontWeight:600,color:p.tx,padding:"2px 12px 10px"}}>Workspace</T>{items.map((t,i)=><div key={i} style={{padding:"8px 12px",borderRadius:10,background:i===0?`${p.ac}12`:"transparent",display:"flex",alignItems:"center",gap:10}}><div style={{width:16,height:16,borderRadius:6,background:i===0?`${p.ac}35`:p.mu+"15",flexShrink:0}}/><T k={`nav${i}`} s={{fontSize:12,color:i===0?p.tx:p.mu,fontWeight:i===0?500:400}}>{t}</T></div>)}</div>;
  }

  /* ---- TABLE ---- */
  if(type==="table"){
    const cols=["Name","Status","Amount"];
    const rows=[["Alice","Active","$1,200"],["Bob","Pending","$840"],["Carol","Active","$2,100"]];
    const hst={fontSize:10,fontWeight:600,color:p.mu,textTransform:"uppercase",letterSpacing:"0.05em"};
    const cst={fontSize:11,color:p.tx};
    const cst2={fontSize:11,color:p.mu};
    if(v===0)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,overflow:"hidden",display:"flex",flexDirection:"column"}}><div style={{display:"flex",padding:"10px 14px",borderBottom:`1px solid ${p.bd}`}}>{cols.map((c,i)=><div key={i} style={{flex:i===0?2:1}}><T k={`h${i}`} s={hst}>{c}</T></div>)}</div>{rows.map((r,ri)=><div key={ri} style={{display:"flex",padding:"8px 14px",background:ri%2===0?"transparent":p.su}}>{r.map((c,ci)=><div key={ci} style={{flex:ci===0?2:1}}><T k={`r${ri}c${ci}`} s={ci===0?cst:cst2}>{c}</T></div>)}</div>)}</div>;
    if(v===1)return <div style={{...b,background:p.card,borderRadius:8,border:`1px solid ${p.bd}`,overflow:"hidden",display:"flex",flexDirection:"column"}}><div style={{display:"flex",padding:"10px 14px",borderBottom:`2px solid ${p.bd}`}}>{cols.map((c,i)=><div key={i} style={{flex:i===0?2:1,borderRight:i<2?`1px solid ${p.bd}`:"none",paddingRight:8}}><T k={`h${i}`} s={hst}>{c}</T></div>)}</div>{rows.map((r,ri)=><div key={ri} style={{display:"flex",padding:"8px 14px",borderBottom:ri<2?`1px solid ${p.bd}`:"none"}}>{r.map((c,ci)=><div key={ci} style={{flex:ci===0?2:1,borderRight:ci<2?`1px solid ${p.bd}`:"none",paddingRight:8}}><T k={`r${ri}c${ci}`} s={ci===0?cst:cst2}>{c}</T></div>)}</div>)}</div>;
    if(v===2)return <div style={{...b,display:"flex",flexDirection:"column"}}><div style={{display:"flex",padding:"8px 4px",borderBottom:`1px solid ${p.bd}`}}>{cols.map((c,i)=><div key={i} style={{flex:i===0?2:1}}><T k={`h${i}`} s={hst}>{c}</T></div>)}</div>{rows.map((r,ri)=><div key={ri} style={{display:"flex",padding:"8px 4px",borderBottom:ri<2?`1px solid ${p.bd}`:"none"}}>{r.map((c,ci)=><div key={ci} style={{flex:ci===0?2:1}}><T k={`r${ri}c${ci}`} s={ci===0?cst:cst2}>{c}</T></div>)}</div>)}</div>;
    const tcols=["ID","STATUS","SIGNAL"];const trows=[["0x7F","ACTIVE","████▓▓"],["0x3A","STANDBY","██▓▓▓▓"],["0xB2","ACTIVE","█████▓"]];
    return <div style={{...b,background:"#0c0c0e",borderRadius:2,border:`1px solid ${p.ac}20`,overflow:"hidden",display:"flex",flexDirection:"column",fontFamily:"'JetBrains Mono',monospace"}}><div style={{display:"flex",padding:"8px 12px",borderBottom:`1px solid ${p.ac}15`,background:`${p.ac}06`}}>{tcols.map((c,i)=><div key={i} style={{flex:i===0?1:1}}><T k={`h${i}`} s={{fontSize:9,fontWeight:600,color:p.ac,opacity:.6,textTransform:"uppercase",letterSpacing:"0.08em"}}>{c}</T></div>)}</div>{trows.map((r,ri)=><div key={ri} style={{display:"flex",padding:"7px 12px",borderBottom:ri<2?`1px solid #ffffff08`:"none",animation:`tp-fadein .3s ease-out ${ri*0.1}s both`}}>{r.map((c,ci)=><div key={ci} style={{flex:1}}><T k={`r${ri}c${ci}`} s={{fontSize:10,color:ci===1?(r[ci]==="ACTIVE"?"#4CAF50":"#888"):ci===2?p.ac+"88":"#aaa"}}>{c}</T></div>)}</div>)}</div>;
  }

  /* ---- ACCORDION ---- */
  if(type==="accordion"){
    const items=[{q:"What is this?",open:true},{q:"How does it work?",open:false},{q:"Pricing plans?",open:false}];
    const chev=(o)=><span style={{fontSize:11,color:p.mu,transform:o?"rotate(90deg)":"rotate(0)",display:"inline-block",transition:"transform .2s"}}>›</span>;
    if(v===0)return <div style={{...b,display:"flex",flexDirection:"column"}}>{items.map((it,i)=><div key={i} style={{borderBottom:i<2?`1px solid ${p.bd}`:"none",padding:"10px 0"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><T k={`q${i}`} s={{fontSize:12,fontWeight:500,color:p.tx}}>{it.q}</T>{chev(it.open)}</div>{it.open&&<div style={{marginTop:6}}><T k={`a${i}`} s={{fontSize:11,color:p.mu,lineHeight:1.5}}>This is the answer to the question above.</T></div>}</div>)}</div>;
    if(v===1)return <div style={{...b,display:"flex",flexDirection:"column",gap:6}}>{items.map((it,i)=><div key={i} style={{background:it.open?p.su:p.card,border:`1px solid ${p.bd}`,borderRadius:10,padding:"10px 12px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><T k={`q${i}`} s={{fontSize:12,fontWeight:500,color:p.tx}}>{it.q}</T>{chev(it.open)}</div>{it.open&&<div style={{marginTop:6}}><T k={`a${i}`} s={{fontSize:11,color:p.mu,lineHeight:1.5}}>This is the answer to the question above.</T></div>}</div>)}</div>;
    return <div style={{...b,display:"flex",flexDirection:"column"}}>{items.map((it,i)=><div key={i} style={{padding:"10px 0",borderBottom:i<2?`1px solid ${p.bd}`:"none"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><T k={`q${i}`} s={{fontSize:12,fontWeight:it.open?600:400,color:it.open?p.ac:p.tx}}>{it.q}</T><span style={{fontSize:13,color:p.mu}}>{it.open?"−":"+"}</span></div>{it.open&&<div style={{marginTop:6}}><T k={`a${i}`} s={{fontSize:11,color:p.mu,lineHeight:1.5}}>This is the answer to the question above.</T></div>}</div>)}</div>;
  }

  /* ---- FOOTER ---- */
  if(type==="footer"){
    const cols=[["Product","Features","Pricing","Docs"],["Company","About","Blog","Careers"]];
    if(v===0)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:"16px 20px",display:"flex",gap:24}}><div style={{flex:1,display:"flex",flexDirection:"column",gap:4}}><T k="brand" s={{fontSize:12,fontWeight:600,color:p.tx,marginBottom:4}}>Brand</T><T k="tagline" s={{fontSize:9,color:p.mu,lineHeight:1.4}}>Building better products</T></div>{cols.map((col,ci)=><div key={ci} style={{flex:1,display:"flex",flexDirection:"column",gap:4}}><T k={`col${ci}`} s={{fontSize:10,fontWeight:600,color:p.tx,marginBottom:2}}>{col[0]}</T>{col.slice(1).map((l,li)=><T key={li} k={`c${ci}l${li}`} s={{fontSize:10,color:p.mu}}>{l}</T>)}</div>)}</div>;
    if(v===1)return <div style={{...b,borderTop:`1px solid ${p.bd}`,padding:"14px 20px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><T k="brand" s={{fontSize:12,fontWeight:600,color:p.tx}}>Tasteprint</T><div style={{display:"flex",gap:16}}>{["Privacy","Terms","Contact"].map((l,i)=><T key={i} k={`link${i}`} s={{fontSize:10,color:p.mu}}>{l}</T>)}</div><T k="copy" s={{fontSize:9,color:p.mu,opacity:.5}}>© 2026</T></div>;
    return <div style={{...b,background:p.tx,borderRadius:12,padding:"16px 20px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><T k="brand" s={{fontSize:13,fontWeight:600,color:p.bg}}>Brand</T><div style={{display:"flex",gap:16}}>{["About","Blog","Contact"].map((l,i)=><T key={i} k={`link${i}`} s={{fontSize:10,color:p.bg,opacity:.5}}>{l}</T>)}</div><div style={{display:"flex",gap:6}}>{[0,1,2].map(i=><Img key={i} k={`social${i}`} s={{width:20,height:20,borderRadius:999,background:`${p.bg}15`}}/>)}</div></div>;
  }

  /* ---- BENTO GRID ---- */
  if(type==="bento-grid"){
    const cell=(r,idx)=>{
      const imgSrc=texts[`img${idx}`];
      const dropImg=e=>{e.preventDefault();e.stopPropagation();if(!editable)return;const file=(e.dataTransfer?.files||[])[0];if(!file||!file.type.startsWith("image/"))return;const rd=new FileReader();rd.onload=rr=>{onText?.(`img${idx}`,rr.target.result)};rd.onerror=()=>{console.error("Failed to read image file")};rd.readAsDataURL(file)};
      const replaceImg=()=>{if(!editable||!imgSrc)return;const inp=document.createElement("input");inp.type="file";inp.accept="image/*";inp.onchange=ev=>{const file=ev.target.files[0];if(!file)return;const rd=new FileReader();rd.onload=rr=>{onText?.(`img${idx}`,rr.target.result)};rd.onerror=()=>{console.error("Failed to read image file")};rd.readAsDataURL(file)};inp.click()};
      return <div style={{background:p.su,borderRadius:12,border:`1px solid ${p.bd}`,overflow:"hidden",position:"relative",display:"flex",alignItems:"center",justifyContent:"center",padding:12,...r}} onDragOver={e=>e.preventDefault()} onDrop={dropImg}>
        {imgSrc&&<img src={imgSrc} onClick={replaceImg} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",cursor:editable?"pointer":"default"}}/>}
        <T k={`t${idx}`} s={{position:"relative",zIndex:1,fontSize:12,color:imgSrc?"#fff":p.mu,fontWeight:500,textShadow:imgSrc?"0 1px 4px rgba(0,0,0,.5)":"none",textAlign:"center"}}>{" "}</T>
      </div>;
    };
    if(v===0)return <div style={{...b,display:"grid",gridTemplateColumns:"1fr 1fr",gridTemplateRows:"1fr 1fr",gap:8}}>{cell({},0)}{cell({},1)}{cell({},2)}{cell({},3)}</div>;
    if(v===1)return <div style={{...b,display:"grid",gridTemplateColumns:"1.4fr 1fr",gridTemplateRows:"1fr 1fr",gap:8}}>{cell({gridRow:"1/3"},0)}{cell({},1)}{cell({},2)}</div>;
    return <div style={{...b,display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gridTemplateRows:"1fr 1fr",gap:8}}>{cell({gridColumn:"1/3"},0)}{cell({},1)}{cell({},2)}{cell({gridColumn:"2/4"},3)}</div>;
  }

  /* ---- DROPDOWN ---- */
  if(type==="dropdown"){
    const items=["Option one","Option two","Option three"];
    if(v===0)return <div style={{...b,display:"flex",flexDirection:"column"}}><div style={{height:36,background:p.card,borderRadius:10,border:`1px solid ${p.bd}`,padding:"0 12px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><T k="sel" s={{fontSize:12,color:p.tx}}>Select...</T><span style={{fontSize:10,color:p.mu}}>▾</span></div><div style={{marginTop:4,background:p.card,borderRadius:10,border:`1px solid ${p.bd}`,boxShadow:`0 8px 24px ${p.tx}08`,overflow:"hidden"}}>{items.map((it,i)=><div key={i} style={{padding:"8px 12px",background:i===0?p.ac+"12":"transparent"}}><T k={`o${i}`} s={{fontSize:12,color:i===0?p.ac:p.tx}}>{it}</T></div>)}</div></div>;
    if(v===1)return <div style={{...b,display:"flex",flexDirection:"column"}}><div style={{height:36,borderBottom:`1.5px solid ${p.bd}`,padding:"0 4px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><T k="sel" s={{fontSize:12,color:p.tx}}>Select...</T><span style={{fontSize:10,color:p.mu}}>▾</span></div><div style={{marginTop:4,background:p.card,border:`1px solid ${p.bd}`,overflow:"hidden"}}>{items.map((it,i)=><div key={i} style={{padding:"8px 12px",borderBottom:i<2?`1px solid ${p.bd}`:"none"}}><T k={`o${i}`} s={{fontSize:12,color:p.tx}}>{it}</T></div>)}</div></div>;
    return <div style={{...b,display:"flex",flexDirection:"column"}}><div style={{height:36,background:p.su,borderRadius:999,padding:"0 14px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><T k="sel" s={{fontSize:12,color:p.tx}}>Select...</T><span style={{fontSize:10,color:p.mu}}>▾</span></div><div style={{marginTop:4,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,boxShadow:`0 8px 24px ${p.tx}08`,overflow:"hidden"}}>{items.map((it,i)=><div key={i} style={{padding:"8px 14px",borderRadius:8,margin:2,background:i===0?p.ac+"12":"transparent"}}><T k={`o${i}`} s={{fontSize:12,color:i===0?p.ac:p.tx}}>{it}</T></div>)}</div></div>;
  }

  /* ---- SELECT ---- */
  if(type==="select"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:10,border:`1.5px solid ${p.bd}`,padding:"0 12px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><T k="val" s={{fontSize:13,color:p.tx}}>Choose option</T><span style={{fontSize:10,color:p.mu}}>▾</span></div>;
    if(v===1)return <div style={{...b,background:p.su,borderRadius:999,padding:"0 16px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><T k="val" s={{fontSize:13,color:p.tx}}>Choose option</T><span style={{fontSize:10,color:p.mu}}>▾</span></div>;
    return <div style={{...b,borderBottom:`2px solid ${p.ac}30`,padding:"0 4px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><T k="val" s={{fontSize:13,color:p.tx}}>Choose option</T><span style={{fontSize:10,color:p.mu}}>▾</span></div>;
  }

  /* ---- CHECKBOX ---- */
  if(type==="checkbox"){
    const items=[{label:"Option A",checked:true},{label:"Option B",checked:false},{label:"Option C",checked:false}];
    const box=(checked,round)=><div style={{width:16,height:16,borderRadius:round?999:4,border:checked?`none`:`1.5px solid ${p.bd}`,background:checked?p.ac:p.card,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{checked&&<svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="#fff" strokeWidth="1.5" strokeLinecap="round"><path d="M2 5l2.5 2.5L8 3"/></svg>}</div>;
    if(v===0)return <div style={{...b,display:"flex",flexDirection:"column",gap:8,justifyContent:"center"}}>{items.map((it,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8}}>{box(it.checked,false)}<T k={`l${i}`} s={{fontSize:12,color:it.checked?p.tx:p.mu}}>{it.label}</T></div>)}</div>;
    if(v===1)return <div style={{...b,display:"flex",flexDirection:"column",gap:8,justifyContent:"center"}}>{items.map((it,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8}}>{box(it.checked,true)}<T k={`l${i}`} s={{fontSize:12,color:it.checked?p.tx:p.mu}}>{it.label}</T></div>)}</div>;
    return <div style={{...b,display:"flex",flexDirection:"column",gap:4,justifyContent:"center"}}>{items.map((it,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"6px 10px",borderRadius:8,background:it.checked?p.ac+"12":"transparent"}}><div style={{width:32,height:18,borderRadius:999,background:it.checked?p.ac:p.mu+"30",padding:2,display:"flex",alignItems:it.checked?"center":"center",justifyContent:it.checked?"flex-end":"flex-start"}}><div style={{width:14,height:14,borderRadius:999,background:"#fff",boxShadow:"0 1px 2px rgba(0,0,0,.1)"}}/></div><T k={`l${i}`} s={{fontSize:12,color:it.checked?p.tx:p.mu}}>{it.label}</T></div>)}</div>;
  }

  /* ---- SLIDER ---- */
  if(type==="slider"){
    const pct=65;
    if(v===0)return <div style={{...b,display:"flex",alignItems:"center"}}><div style={{width:"100%",height:6,borderRadius:999,background:p.su,position:"relative"}}><div style={{width:`${pct}%`,height:"100%",borderRadius:999,background:p.ac}}/><div style={{position:"absolute",left:`${pct}%`,top:"50%",transform:"translate(-50%,-50%)",width:16,height:16,borderRadius:999,background:p.card,border:`2px solid ${p.ac}`,boxShadow:`0 1px 4px ${p.tx}12`}}/></div></div>;
    if(v===1)return <div style={{...b,display:"flex",alignItems:"center"}}><div style={{width:"100%",height:3,borderRadius:999,background:p.su,position:"relative"}}><div style={{width:`${pct}%`,height:"100%",borderRadius:999,background:p.ac}}/><div style={{position:"absolute",left:`${pct}%`,top:"50%",transform:"translate(-50%,-50%)",width:12,height:12,borderRadius:999,background:p.ac}}/></div></div>;
    return <div style={{...b,display:"flex",alignItems:"center"}}><div style={{width:"100%",height:6,borderRadius:999,background:p.su,position:"relative",display:"flex",alignItems:"center"}}>{[0,25,50,75,100].map(s=><div key={s} style={{position:"absolute",left:`${s}%`,width:2,height:10,background:p.mu+"30",borderRadius:1,transform:"translateX(-50%)"}}/>)}<div style={{width:`${pct}%`,height:"100%",borderRadius:999,background:p.ac,position:"absolute"}}/><div style={{position:"absolute",left:`${pct}%`,top:"50%",transform:"translate(-50%,-50%)",width:14,height:14,borderRadius:4,background:p.ac}}/></div></div>;
  }

  /* ---- ALERT ---- */
  if(type==="alert"){
    const configs=[
      {bg:"#EBF5FF",bc:"#3B82F6",ic:"ℹ",tx:"#1E40AF",label:"Info: Check the docs for details."},
      {bg:"#FFF8E1",bc:"#F59E0B",ic:"⚠",tx:"#92400E",label:"Warning: This action cannot be undone."},
      {bg:"#ECFDF5",bc:"#10B981",ic:"✓",tx:"#065F46",label:"Success: Your changes have been saved."},
      {bg:"#FEF2F2",bc:"#EF4444",ic:"✕",tx:"#991B1B",label:"Error: Something went wrong."},
    ];
    const c=configs[v]||configs[0];
    return <div style={{...b,background:c.bg,borderRadius:10,borderLeft:`3px solid ${c.bc}`,padding:"0 14px",display:"flex",alignItems:"center",gap:10,animation:"tp-slidein .3s ease-out"}}><span style={{fontSize:14,color:c.bc}}>{c.ic}</span><T k="label" s={{fontSize:12,color:c.tx,fontWeight:500}}>{c.label}</T></div>;
  }

  /* ---- PAGINATION ---- */
  if(type==="pagination"){
    if(v===0)return <div style={{...b,display:"flex",alignItems:"center",justifyContent:"center",gap:4}}>{["‹",1,2,3,"…",8,"›"].map((pg,i)=><div key={i} style={{width:28,height:28,borderRadius:8,background:pg===2?p.ac:"transparent",border:typeof pg==="number"&&pg!==2?`1px solid ${p.bd}`:"none",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><T k={`p${i}`} s={{fontSize:11,color:pg===2?"#fff":p.mu,fontWeight:pg===2?600:400}}>{pg}</T></div>)}</div>;
    if(v===1)return <div style={{...b,display:"flex",alignItems:"center",justifyContent:"center",gap:6}}>{[1,2,3,4,5].map((pg,i)=><div key={i} style={{width:8,height:8,borderRadius:999,background:pg===2?p.ac:p.mu+"30"}}/>)}</div>;
    return <div style={{...b,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 8px"}}><T k="prev" s={{fontSize:11,color:p.mu}}>← Previous</T><T k="info" s={{fontSize:11,color:p.mu}}>Page 2 of 8</T><T k="next" s={{fontSize:11,color:p.ac,fontWeight:500}}>Next →</T></div>;
  }

  /* ---- PRICING CARD ---- */
  if(type==="pricing-card"){
    const features=["10 projects","5GB storage","Priority support","Custom domain"];
    if(v===0)return <div style={{...b,background:p.card,borderRadius:16,border:`1px solid ${p.bd}`,padding:24,display:"flex",flexDirection:"column",gap:12}}><T k="plan" s={{fontSize:11,color:p.mu,fontWeight:600,textTransform:"uppercase",letterSpacing:"0.05em"}}>Pro</T><div style={{display:"flex",alignItems:"baseline",gap:2}}><T k="price" s={{fontSize:32,fontWeight:700,color:p.tx}}>$29</T><T k="period" s={{fontSize:12,color:p.mu}}>/mo</T></div><div style={{height:1,background:p.bd,margin:"4px 0"}}/><div style={{flex:1,display:"flex",flexDirection:"column",gap:8}}>{features.map((f,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:14,height:14,borderRadius:999,background:p.ac+"18",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:8,color:p.ac}}>✓</span></div><T k={`f${i}`} s={{fontSize:12,color:p.tx}}>{f}</T></div>)}</div><div style={{height:38,borderRadius:10,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{fontSize:12,color:"#fff",fontWeight:600}}>Get started</T></div></div>;
    if(v===1)return <div style={{...b,background:p.ac,borderRadius:16,padding:24,display:"flex",flexDirection:"column",gap:12,boxShadow:`0 8px 32px ${p.ac}30`,transition:"box-shadow .4s,transform .3s"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><T k="plan" s={{fontSize:11,color:"#fff",fontWeight:600,textTransform:"uppercase",letterSpacing:"0.05em",opacity:.8}}>Pro</T><div style={{background:"#fff22",borderRadius:999,padding:"2px 8px"}}><T k="badge" s={{fontSize:9,color:"#fff",fontWeight:600}}>POPULAR</T></div></div><div style={{display:"flex",alignItems:"baseline",gap:2}}><T k="price" s={{fontSize:32,fontWeight:700,color:"#fff"}}>$29</T><T k="period" s={{fontSize:12,color:"#fff",opacity:.6}}>/mo</T></div><div style={{height:1,background:"#fff2",margin:"4px 0"}}/><div style={{flex:1,display:"flex",flexDirection:"column",gap:8}}>{features.map((f,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8}}><span style={{fontSize:10,color:"#fff",opacity:.7}}>✓</span><T k={`f${i}`} s={{fontSize:12,color:"#fff",opacity:.9}}>{f}</T></div>)}</div><div style={{height:38,borderRadius:10,background:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{fontSize:12,color:p.ac,fontWeight:600}}>Get started</T></div></div>;
    return <div style={{...b,background:p.card,borderRadius:12,padding:24,display:"flex",flexDirection:"column",gap:14}}><T k="plan" s={{fontSize:16,fontWeight:600,color:p.tx}}>Pro</T><div style={{display:"flex",alignItems:"baseline",gap:2}}><T k="price" s={{fontSize:28,fontWeight:600,color:p.tx}}>$29</T><T k="period" s={{fontSize:12,color:p.mu}}>/mo</T></div><div style={{flex:1,display:"flex",flexDirection:"column",gap:6}}>{features.map((f,i)=><T key={i} k={`f${i}`} s={{fontSize:12,color:p.mu}}>• {f}</T>)}</div><div style={{height:36,borderRadius:8,border:`1.5px solid ${p.ac}`,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{fontSize:12,color:p.ac,fontWeight:500}}>Choose plan</T></div></div>;
  }

  /* ---- PRODUCT CARD ---- */
  if(type==="product-card"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,overflow:"hidden",display:"flex",flexDirection:"column"}}><Img k="media" s={{height:"50%",background:p.su}}/><div style={{padding:14,display:"flex",flexDirection:"column",gap:6,flex:1}}><T k="title" s={{fontSize:13,fontWeight:600,color:p.tx}}>Product Name</T><T k="desc" s={{fontSize:10,color:p.mu}}>Short product description</T><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginTop:"auto"}}><T k="price" s={{fontSize:16,fontWeight:700,color:p.tx}}>$49.00</T><div style={{height:30,width:72,borderRadius:8,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:"#fff",fontSize:10,fontWeight:600}}>Add</T></div></div></div></div>;
    if(v===1)return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,overflow:"hidden",display:"flex",flexDirection:"column",position:"relative"}}><div style={{position:"absolute",top:10,left:10,background:"#E05050",borderRadius:6,padding:"2px 8px",zIndex:2}}><T k="badge" s={{fontSize:9,color:"#fff",fontWeight:600}}>SALE</T></div><Img k="media" s={{height:"50%",background:p.su}}/><div style={{padding:14,display:"flex",flexDirection:"column",gap:6,flex:1}}><T k="title" s={{fontSize:13,fontWeight:600,color:p.tx}}>Product Name</T><div style={{display:"flex",alignItems:"center",gap:8,marginTop:"auto"}}><T k="price" s={{fontSize:16,fontWeight:700,color:p.ac}}>$29.00</T><T k="orig" s={{fontSize:12,color:p.mu,textDecoration:"line-through"}}>$49.00</T></div></div></div>;
    return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,display:"flex",gap:0,overflow:"hidden"}}><Img k="media" s={{width:"40%",background:p.su,flexShrink:0}}/><div style={{padding:14,display:"flex",flexDirection:"column",gap:6,flex:1}}><T k="title" s={{fontSize:13,fontWeight:600,color:p.tx}}>Product Name</T><T k="desc" s={{fontSize:10,color:p.mu,lineHeight:1.5}}>Short description</T><div style={{marginTop:"auto",display:"flex",alignItems:"center",justifyContent:"space-between"}}><T k="price" s={{fontSize:15,fontWeight:700,color:p.tx}}>$49.00</T><div style={{height:28,width:66,borderRadius:6,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:"#fff",fontSize:10,fontWeight:600}}>Add</T></div></div></div></div>;
  }

  /* ---- CART ITEM ---- */
  if(type==="cart-item"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:12,display:"flex",gap:12,alignItems:"center"}}><Img k="thumb" s={{width:48,height:48,borderRadius:8,background:p.su,flexShrink:0}}/><div style={{flex:1,display:"flex",flexDirection:"column",gap:2}}><T k="name" s={{fontSize:12,fontWeight:600,color:p.tx}}>Product Name</T><T k="variant" s={{fontSize:10,color:p.mu}}>Size M · Black</T></div><div style={{display:"flex",alignItems:"center",gap:6,border:`1px solid ${p.bd}`,borderRadius:6,padding:"2px 6px"}}><span style={{fontSize:12,color:p.mu,cursor:"pointer"}}>−</span><T k="qty" s={{fontSize:11,fontWeight:500,color:p.tx,minWidth:16,textAlign:"center"}}>1</T><span style={{fontSize:12,color:p.mu,cursor:"pointer"}}>+</span></div><T k="price" s={{fontSize:13,fontWeight:600,color:p.tx,minWidth:50,textAlign:"right"}}>$49.00</T></div>;
    return <div style={{...b,borderBottom:`1px solid ${p.bd}`,padding:"10px 0",display:"flex",gap:10,alignItems:"center"}}><Img k="thumb" s={{width:36,height:36,borderRadius:6,background:p.su,flexShrink:0}}/><T k="name" s={{flex:1,fontSize:11,fontWeight:500,color:p.tx}}>Product Name</T><T k="qty" s={{fontSize:10,color:p.mu}}>×1</T><T k="price" s={{fontSize:12,fontWeight:600,color:p.tx}}>$49</T></div>;
  }

  /* ---- FEATURE TABLE ---- */
  if(type==="feature-table"){
    const tiers=["Free","Pro","Team"];const feats=["Projects","Storage","Support","API"];const vals=[["3","10","∞"],["1GB","10GB","100GB"],["Email","Priority","24/7"],["—","✓","✓"]];
    const hst={fontSize:10,fontWeight:600,textTransform:"uppercase",letterSpacing:"0.05em"};
    if(v===0)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,overflow:"hidden",display:"flex",flexDirection:"column"}}><div style={{display:"flex",borderBottom:`1px solid ${p.bd}`}}><div style={{flex:1.5,padding:"8px 12px"}}><span style={{...hst,color:p.mu}}>Feature</span></div>{tiers.map((t,i)=><div key={i} style={{flex:1,padding:"8px 8px",textAlign:"center"}}><T k={`t${i}`} s={{...hst,color:i===1?p.ac:p.mu}}>{t}</T></div>)}</div>{feats.map((f,fi)=><div key={fi} style={{display:"flex",borderBottom:fi<3?`1px solid ${p.bd}`:"none"}}><div style={{flex:1.5,padding:"6px 12px"}}><T k={`f${fi}`} s={{fontSize:11,color:p.tx}}>{f}</T></div>{vals[fi].map((val,vi)=><div key={vi} style={{flex:1,padding:"6px 8px",textAlign:"center"}}><span style={{fontSize:11,color:val==="✓"?"#4CAF50":val==="—"?p.mu:p.tx}}>{val}</span></div>)}</div>)}</div>;
    if(v===1)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,overflow:"hidden",display:"flex",flexDirection:"column"}}><div style={{display:"flex",borderBottom:`1px solid ${p.bd}`}}><div style={{flex:1.5,padding:"8px 12px"}}></div>{tiers.map((t,i)=><div key={i} style={{flex:1,padding:"8px 8px",textAlign:"center",background:i===1?p.ac+"0a":"transparent"}}><T k={`t${i}`} s={{...hst,color:i===1?p.ac:p.mu}}>{t}</T></div>)}</div>{feats.map((f,fi)=><div key={fi} style={{display:"flex",borderBottom:fi<3?`1px solid ${p.bd}`:"none"}}><div style={{flex:1.5,padding:"6px 12px"}}><T k={`f${fi}`} s={{fontSize:11,color:p.tx}}>{f}</T></div>{vals[fi].map((val,vi)=><div key={vi} style={{flex:1,padding:"6px 8px",textAlign:"center",background:vi===1?p.ac+"0a":"transparent"}}><span style={{fontSize:11,color:val==="✓"?"#4CAF50":val==="—"?p.mu:p.tx}}>{val}</span></div>)}</div>)}</div>;
    return <div style={{...b,display:"flex",flexDirection:"column"}}><div style={{display:"flex",borderBottom:`1px solid ${p.bd}`,paddingBottom:6}}><div style={{flex:1.5}}></div>{tiers.map((t,i)=><div key={i} style={{flex:1,textAlign:"center"}}><T k={`t${i}`} s={{fontSize:11,fontWeight:600,color:p.tx}}>{t}</T></div>)}</div>{feats.map((f,fi)=><div key={fi} style={{display:"flex",padding:"5px 0"}}><div style={{flex:1.5}}><T k={`f${fi}`} s={{fontSize:11,color:p.mu}}>{f}</T></div>{vals[fi].map((val,vi)=><div key={vi} style={{flex:1,textAlign:"center"}}><span style={{fontSize:11,color:val==="✓"?p.ac:val==="—"?p.mu+"60":p.tx}}>{val}</span></div>)}</div>)}</div>;
  }

  /* ---- PROMO BANNER ---- */
  if(type==="promo-banner"){
    if(v===0)return <div style={{...b,background:`linear-gradient(135deg,${p.ac},${p.ac2},${p.ac})`,backgroundSize:"200% 200%",animation:"tp-gradient-shift 3s ease infinite",borderRadius:12,padding:"0 20px",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div style={{display:"flex",alignItems:"center",gap:12}}><T k="text" s={{fontSize:13,fontWeight:600,color:"#fff"}}>Summer Sale — 30% off</T><div style={{background:"#fff3",borderRadius:6,padding:"3px 10px"}}><T k="code" s={{fontSize:11,fontWeight:600,color:"#fff",letterSpacing:"0.06em"}}>SUMMER30</T></div></div><div style={{height:32,width:80,borderRadius:8,background:"#fff",display:"flex",alignItems:"center",justifyContent:"center"}}><T k="cta" s={{color:p.ac,fontSize:11,fontWeight:600}}>Shop now</T></div></div>;
    return <div style={{...b,borderRadius:999,border:`1px solid ${p.bd}`,background:p.su,padding:"0 20px",display:"flex",alignItems:"center",justifyContent:"center",gap:12}}><T k="text" s={{fontSize:12,fontWeight:500,color:p.tx}}>Use code</T><div style={{background:p.ac+"14",borderRadius:4,padding:"2px 8px"}}><T k="code" s={{fontSize:11,fontWeight:600,color:p.ac,letterSpacing:"0.04em"}}>SAVE20</T></div><T k="cta" s={{fontSize:12,fontWeight:500,color:p.ac}}>→</T></div>;
  }

  /* ---- ORDER SUMMARY ---- */
  if(type==="order-summary"){
    const lines=[{l:"Subtotal",v:"$98.00"},{l:"Shipping",v:"$5.00"},{l:"Tax",v:"$8.24"}];
    if(v===0)return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,padding:18,display:"flex",flexDirection:"column",gap:8}}><T k="title" s={{fontSize:14,fontWeight:600,color:p.tx}}>Order Summary</T><div style={{height:1,background:p.bd}}/>{lines.map((l,i)=><div key={i} style={{display:"flex",justifyContent:"space-between"}}><T k={`l${i}`} s={{fontSize:12,color:p.mu}}>{l.l}</T><T k={`v${i}`} s={{fontSize:12,color:p.tx}}>{l.v}</T></div>)}<div style={{height:1,background:p.bd}}/><div style={{display:"flex",justifyContent:"space-between"}}><T k="total_label" s={{fontSize:13,fontWeight:600,color:p.tx}}>Total</T><T k="total" s={{fontSize:15,fontWeight:700,color:p.tx}}>$111.24</T></div><div style={{height:36,borderRadius:10,background:p.ac,display:"flex",alignItems:"center",justifyContent:"center",marginTop:4}}><T k="cta" s={{color:"#fff",fontSize:12,fontWeight:600}}>Checkout</T></div></div>;
    return <div style={{...b,padding:12,display:"flex",flexDirection:"column",gap:6}}>{lines.map((l,i)=><div key={i} style={{display:"flex",justifyContent:"space-between"}}><T k={`l${i}`} s={{fontSize:11,color:p.mu}}>{l.l}</T><T k={`v${i}`} s={{fontSize:11,color:p.tx}}>{l.v}</T></div>)}<div style={{height:1,background:p.bd,margin:"2px 0"}}/><div style={{display:"flex",justifyContent:"space-between"}}><T k="total_label" s={{fontSize:12,fontWeight:600,color:p.tx}}>Total</T><T k="total" s={{fontSize:13,fontWeight:700,color:p.ac}}>$111.24</T></div></div>;
  }

  /* ---- RATING ---- */
  if(type==="rating"){
    const stars=(n,sz=14)=><span style={{fontSize:sz,letterSpacing:2}}>{Array(5).fill(0).map((_,i)=><span key={i} style={{color:i<n?p.ac:p.mu+"30"}}>{i<n?"★":"☆"}</span>)}</span>;
    if(v===0)return <div style={{...b,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:6}}>{stars(4,18)}<div style={{display:"flex",alignItems:"center",gap:6}}><T k="score" s={{fontSize:14,fontWeight:600,color:p.tx}}>4.0</T><T k="count" s={{fontSize:11,color:p.mu}}>(128 reviews)</T></div></div>;
    if(v===1)return <div style={{...b,display:"flex",alignItems:"center",gap:8}}>{stars(4,14)}<T k="score" s={{fontSize:13,fontWeight:600,color:p.tx}}>4.0</T><T k="count" s={{fontSize:10,color:p.mu}}>128</T></div>;
    return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:14,display:"flex",flexDirection:"column",gap:8}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>{stars(5,14)}<T k="date" s={{fontSize:10,color:p.mu}}>2 days ago</T></div><T k="text" s={{fontSize:11,color:p.tx,lineHeight:1.5}}>Excellent quality, fast shipping. Would definitely buy again!</T><div style={{display:"flex",alignItems:"center",gap:6}}><Img k="avatar" s={{width:20,height:20,borderRadius:999,background:p.ac+"20"}}/><T k="author" s={{fontSize:10,fontWeight:500,color:p.mu}}>Jane D.</T></div></div>;
  }

  /* ---- RECEIPT ---- */
  if(type==="receipt"){
    const items=[{n:"Widget Pro",q:"2",p:"$49.00"},{n:"Adapter",q:"1",p:"$12.00"}];
    if(v===0)return <div style={{...b,background:p.card,borderRadius:4,border:`2px dashed ${p.bd}`,padding:18,display:"flex",flexDirection:"column",gap:8,fontFamily:"'JetBrains Mono',monospace"}}><div style={{textAlign:"center"}}><T k="store" s={{fontSize:12,fontWeight:600,color:p.tx}}>ACME STORE</T><div style={{fontSize:9,color:p.mu,marginTop:2}}>Order #12847</div></div><div style={{borderTop:`1px dashed ${p.bd}`,margin:"4px 0"}}/>{items.map((it,i)=><div key={i} style={{display:"flex",justifyContent:"space-between"}}><div><T k={`n${i}`} s={{fontSize:10,color:p.tx}}>{it.n}</T><span style={{fontSize:9,color:p.mu}}> ×{it.q}</span></div><T k={`p${i}`} s={{fontSize:10,color:p.tx}}>{it.p}</T></div>)}<div style={{borderTop:`1px dashed ${p.bd}`,margin:"4px 0"}}/><div style={{display:"flex",justifyContent:"space-between"}}><T k="total_l" s={{fontSize:11,fontWeight:600,color:p.tx}}>TOTAL</T><T k="total" s={{fontSize:11,fontWeight:600,color:p.tx}}>$110.00</T></div><div style={{textAlign:"center",marginTop:8}}><div style={{fontSize:8,color:p.mu,letterSpacing:"0.1em"}}>THANK YOU FOR YOUR PURCHASE</div></div></div>;
    return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,padding:18,display:"flex",flexDirection:"column",gap:8}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><T k="store" s={{fontSize:13,fontWeight:600,color:p.tx}}>Order #12847</T><div style={{background:"#4CAF5018",borderRadius:6,padding:"2px 8px"}}><span style={{fontSize:10,color:"#4CAF50",fontWeight:500}}>Paid</span></div></div>{items.map((it,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:28,height:28,borderRadius:6,background:p.su}}/><div><T k={`n${i}`} s={{fontSize:11,fontWeight:500,color:p.tx}}>{it.n}</T><div style={{fontSize:9,color:p.mu}}>Qty: {it.q}</div></div></div><T k={`p${i}`} s={{fontSize:11,fontWeight:500,color:p.tx}}>{it.p}</T></div>)}<div style={{height:1,background:p.bd}}/><div style={{display:"flex",justifyContent:"space-between"}}><T k="total_l" s={{fontSize:12,fontWeight:600,color:p.tx}}>Total</T><T k="total" s={{fontSize:13,fontWeight:700,color:p.tx}}>$110.00</T></div></div>;
  }

  /* ---- SUB TOGGLE ---- */
  if(type==="sub-toggle"){
    if(v===0)return <div style={{...b,display:"flex",gap:8}}><div style={{flex:1,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,padding:14,display:"flex",flexDirection:"column",gap:4}}><T k="plan0" s={{fontSize:12,fontWeight:600,color:p.tx}}>Monthly</T><T k="price0" s={{fontSize:18,fontWeight:700,color:p.tx}}>$29</T><T k="sub0" s={{fontSize:10,color:p.mu}}>per month</T></div><div style={{flex:1,background:p.ac+"0a",borderRadius:12,border:`2px solid ${p.ac}`,padding:14,display:"flex",flexDirection:"column",gap:4,position:"relative"}}><div style={{position:"absolute",top:-8,right:10,background:p.ac,borderRadius:4,padding:"1px 6px"}}><span style={{fontSize:8,color:"#fff",fontWeight:600}}>SAVE 20%</span></div><T k="plan1" s={{fontSize:12,fontWeight:600,color:p.tx}}>Annual</T><T k="price1" s={{fontSize:18,fontWeight:700,color:p.ac}}>$23</T><T k="sub1" s={{fontSize:10,color:p.mu}}>per month</T></div></div>;
    return <div style={{...b,display:"flex",alignItems:"center",justifyContent:"center",gap:12}}><T k="plan0" s={{fontSize:12,fontWeight:500,color:p.mu}}>Monthly</T><div style={{width:44,height:24,borderRadius:999,background:p.ac,padding:2,display:"flex",justifyContent:"flex-end"}}><div style={{width:20,height:20,borderRadius:999,background:"#fff"}}/></div><div style={{display:"flex",alignItems:"center",gap:6}}><T k="plan1" s={{fontSize:12,fontWeight:600,color:p.tx}}>Annual</T><div style={{background:p.ac+"14",borderRadius:4,padding:"1px 6px"}}><T k="badge" s={{fontSize:9,fontWeight:600,color:p.ac}}>-20%</T></div></div></div>;
  }

  /* ---- TOOLTIP ---- */
  if(type==="tooltip"){
    if(v===0)return <div style={{...b,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"flex-end",gap:4}}><div style={{background:p.card,borderRadius:8,border:`1px solid ${p.bd}`,padding:"6px 12px",boxShadow:`0 4px 12px ${p.tx}08`}}><T k="label" s={{fontSize:11,color:p.tx}}>Tooltip text</T></div><div style={{width:8,height:8,background:p.card,border:`1px solid ${p.bd}`,borderTop:"none",borderLeft:"none",transform:"rotate(45deg)",marginTop:-6}}/></div>;
    if(v===1)return <div style={{...b,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"flex-end",gap:4}}><div style={{background:p.tx,borderRadius:6,padding:"6px 12px"}}><T k="label" s={{fontSize:11,color:p.bg}}>Tooltip text</T></div><div style={{width:8,height:8,background:p.tx,transform:"rotate(45deg)",marginTop:-6}}/></div>;
    return <div style={{...b,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"flex-end",gap:0}}><div style={{background:p.card,borderRadius:8,border:`1px solid ${p.bd}`,padding:"6px 12px",boxShadow:`0 4px 12px ${p.tx}08`,position:"relative"}}><T k="label" s={{fontSize:11,color:p.tx}}>Tooltip text</T></div><svg width="12" height="6" viewBox="0 0 12 6" style={{marginTop:-1}}><path d="M0 0L6 6L12 0" fill={p.card} stroke={p.bd} strokeWidth="1"/></svg></div>;
  }

  /* ---- BREADCRUMB ---- */
  if(type==="breadcrumb"){
    const items=["Home","Products","Details"];
    const sep=v===0?" / ":v===1?" › ":"  •  ";
    return <div style={{...b,display:"flex",alignItems:"center",gap:0}}>{items.map((it,i)=><React.Fragment key={i}>{i>0&&<span style={{fontSize:11,color:p.mu,opacity:.4}}>{sep}</span>}<T k={`b${i}`} s={{fontSize:12,color:i===items.length-1?p.tx:p.mu,fontWeight:i===items.length-1?500:400}}>{it}</T></React.Fragment>)}</div>;
  }

  /* ---- SKELETON ---- */
  if(type==="skeleton"){
    const shimmer={background:`linear-gradient(90deg,${p.su} 25%,${p.bd}40 50%,${p.su} 75%)`,backgroundSize:"200% 100%",borderRadius:8,animation:"tp-shimmer 1.5s ease infinite"};
    if(v===0)return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,padding:16,display:"flex",flexDirection:"column",gap:10}}><div style={{...shimmer,height:14,width:"50%"}}/><div style={{...shimmer,height:10,width:"80%"}}/><div style={{...shimmer,height:10,width:"65%"}}/><div style={{...shimmer,height:40,width:"100%",borderRadius:10,marginTop:4}}/></div>;
    if(v===1)return <div style={{...b,display:"flex",flexDirection:"column",gap:10}}>{[0,1,2].map(i=><div key={i} style={{display:"flex",gap:10,alignItems:"center"}}><div style={{...shimmer,width:36,height:36,borderRadius:999,flexShrink:0}}/><div style={{flex:1,display:"flex",flexDirection:"column",gap:6}}><div style={{...shimmer,height:10,width:`${60+i*10}%`}}/><div style={{...shimmer,height:8,width:`${80-i*10}%`}}/></div></div>)}</div>;
    return <div style={{...b,display:"flex",gap:14,alignItems:"center"}}><div style={{...shimmer,width:56,height:56,borderRadius:999,flexShrink:0}}/><div style={{flex:1,display:"flex",flexDirection:"column",gap:8}}><div style={{...shimmer,height:12,width:"40%"}}/><div style={{...shimmer,height:9,width:"70%"}}/><div style={{...shimmer,height:9,width:"55%"}}/></div></div>;
  }

  /* ---- DASH-PANEL (Variant.com inspired) ---- */
  if(type==="dash-panel"){
    const bars=[65,42,78,35,55,88,48];
    if(v===0)return <div style={{...b,background:"#0c0c0e",borderRadius:4,border:`1px solid ${p.ac}20`,padding:14,display:"flex",flexDirection:"column",gap:8,fontFamily:"'JetBrains Mono',monospace"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><T k="title" s={{fontSize:10,color:p.ac,fontWeight:600,textTransform:"uppercase",letterSpacing:"0.08em"}}>TELEMETRY</T><div style={{display:"flex",alignItems:"center",gap:4}}><div style={{width:5,height:5,borderRadius:999,background:"#4CAF50",animation:"tp-pulse 2s ease infinite"}}/><T k="status" s={{fontSize:8,color:"#4CAF50",letterSpacing:"0.05em"}}>LIVE</T></div></div><div style={{display:"flex",gap:3,alignItems:"flex-end",flex:1,padding:"8px 0"}}>{bars.map((h,i)=><div key={i} style={{flex:1,background:p.ac,opacity:i===bars.length-1?.8:.3,borderRadius:1,height:`${h}%`,transformOrigin:"bottom",animation:`tp-bar-grow .6s ease-out ${i*0.08}s both`}}/>)}</div><div style={{display:"flex",justifyContent:"space-between"}}><T k="metric1" s={{fontSize:9,color:"#666"}}>PKT: 2,847</T><T k="metric2" s={{fontSize:9,color:"#666"}}>LAT: 12ms</T></div></div>;
    if(v===1)return <div style={{...b,background:"#0c0c0e",borderRadius:4,border:`1px solid ${p.ac}20`,padding:14,display:"flex",flexDirection:"column",gap:10,fontFamily:"'JetBrains Mono',monospace"}}><T k="title" s={{fontSize:10,color:p.ac,fontWeight:600,letterSpacing:"0.06em"}}>SIGNAL CAPTURE</T><div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{position:"relative",width:90,height:90}}><svg width="90" height="90" viewBox="0 0 90 90"><circle cx="45" cy="45" r="38" fill="none" stroke={p.ac+"15"} strokeWidth="4"/><circle cx="45" cy="45" r="38" fill="none" stroke={p.ac} strokeWidth="4" strokeDasharray={`${0.72*238} ${238}`} strokeLinecap="round" transform="rotate(-90 45 45)" style={{animation:"tp-ring 1s ease-out forwards"}}/></svg><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><T k="value" s={{fontSize:18,fontWeight:600,color:p.ac}}>72%</T><T k="sub" s={{fontSize:8,color:"#555"}}>SIGNAL</T></div></div></div><div style={{display:"flex",gap:8}}>{[{l:"IN",v:"1.2K"},{l:"OUT",v:"847"},{l:"ERR",v:"3"}].map((m,i)=><div key={i} style={{flex:1,padding:"4px 0",borderTop:`1px solid ${p.ac}15`,textAlign:"center"}}><div style={{fontSize:7,color:"#555",letterSpacing:"0.08em"}}>{m.l}</div><T k={`m${i}`} s={{fontSize:10,color:i===2?"#E05050":p.ac,opacity:.8}}>{m.v}</T></div>)}</div></div>;
    return <div style={{...b,background:"#0c0c0e",borderRadius:4,border:`1px solid ${p.ac}15`,padding:14,display:"flex",flexDirection:"column",gap:8,fontFamily:"'JetBrains Mono',monospace"}}><T k="title" s={{fontSize:10,color:"#888",fontWeight:500}}>System</T><T k="value" s={{fontSize:28,fontWeight:600,color:p.ac,letterSpacing:"-0.02em",animation:"tp-count .5s ease-out"}}>847ms</T><div style={{flex:1,display:"flex",alignItems:"flex-end"}}><svg style={{width:"100%",height:"100%"}} viewBox="0 0 100 40" preserveAspectRatio="none"><path d="M0,35 Q10,30 20,28 T40,20 T60,25 T80,15 T100,18" fill="none" stroke={p.ac+"50"} strokeWidth="1.5" style={{strokeDasharray:200,animation:"tp-draw 1.2s ease-out forwards"}}/><path d="M0,35 Q10,30 20,28 T40,20 T60,25 T80,15 T100,18 L100,40 L0,40 Z" fill={p.ac+"08"} style={{animation:"tp-fadein .8s ease-out .4s both"}}/></svg></div><T k="sub" s={{fontSize:9,color:"#555"}}>avg response · last 24h</T></div>;
  }

  /* ---- CHART ---- */
  if(type==="chart"){
    if(v===0){const bars=[55,80,45,90,65,75];return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,padding:16,display:"flex",flexDirection:"column"}}><T k="title" s={{fontSize:12,fontWeight:600,color:p.tx,marginBottom:8}}>Chart title</T><div style={{flex:1,display:"flex",alignItems:"flex-end",gap:8,paddingBottom:4}}>{bars.map((h,i)=><div key={i} style={{flex:1,height:`${h}%`,background:i===3?p.ac:p.ac+"30",borderRadius:4,transformOrigin:"bottom",animation:`tp-bar-grow .5s ease-out ${i*0.08}s both`}}/> )}</div></div>}
    if(v===1){const pts=[[0,60],[20,40],[40,65],[60,30],[80,55],[100,20]];const path="M"+pts.map(([x,y])=>`${x},${y}`).join(" L");return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,padding:16,display:"flex",flexDirection:"column"}}><T k="title" s={{fontSize:12,fontWeight:600,color:p.tx,marginBottom:8}}>Chart title</T><svg style={{flex:1,width:"100%"}} viewBox="0 0 100 80" preserveAspectRatio="none"><path d={path} fill="none" stroke={p.ac} strokeWidth="2" strokeLinejoin="round" style={{strokeDasharray:200,animation:"tp-draw 1.2s ease-out forwards"}}/><path d={path+" L100,80 L0,80 Z"} fill={p.ac+"12"} style={{animation:"tp-fadein .6s ease-out .5s both"}}/></svg></div>}
    const slices=[{pct:40,color:p.ac},{pct:25,color:p.ac2},{pct:20,color:p.mu+"50"},{pct:15,color:p.su}];
    let acc=0;return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,padding:16,display:"flex",flexDirection:"column",gap:8}}><T k="title" s={{fontSize:12,fontWeight:600,color:p.tx}}>Chart title</T><div style={{display:"flex",alignItems:"center",gap:16,flex:1}}><svg width="80" height="80" viewBox="0 0 80 80">{slices.map((s,i)=>{const start=acc;acc+=s.pct;const a1=(start/100)*Math.PI*2-Math.PI/2;const a2=((start+s.pct)/100)*Math.PI*2-Math.PI/2;const large=s.pct>50?1:0;return<path key={i} d={`M40,40 L${40+30*Math.cos(a1)},${40+30*Math.sin(a1)} A30,30 0 ${large},1 ${40+30*Math.cos(a2)},${40+30*Math.sin(a2)} Z`} fill={s.color}/>})}</svg><div style={{display:"flex",flexDirection:"column",gap:6}}>{slices.map((s,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:8,height:8,borderRadius:2,background:s.color}}/><T k={`leg${i}`} s={{fontSize:10,color:p.mu}}>{s.pct}%</T></div>)}</div></div></div>;
  }

  /* ---- TESTIMONIAL ---- */
  if(type==="testimonial"){
    if(v===0)return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,padding:18,display:"flex",flexDirection:"column",gap:10}}><span style={{fontSize:24,color:p.ac,opacity:.3,lineHeight:1}}>"</span><T k="quote" s={{fontSize:12,color:p.tx,lineHeight:1.5,fontStyle:"italic"}}>This product changed how we work. Highly recommend it.</T><div style={{display:"flex",alignItems:"center",gap:8,marginTop:"auto"}}><Img k="avatar" s={{width:28,height:28,borderRadius:999,background:p.ac+"20"}}/><div><T k="name" s={{fontSize:11,fontWeight:600,color:p.tx}}>Jane Doe</T><T k="role" s={{fontSize:10,color:p.mu,display:"block"}}>CEO, Acme</T></div></div></div>;
    if(v===1)return <div style={{...b,display:"flex",flexDirection:"column",gap:8,padding:"8px 0"}}><T k="quote" s={{fontSize:13,color:p.tx,lineHeight:1.5}}>This product changed how we work.</T><div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:4,height:4,borderRadius:999,background:p.ac}}/><T k="name" s={{fontSize:11,color:p.mu}}>Jane Doe, CEO</T></div></div>;
    return <div style={{...b,background:p.su,borderRadius:16,padding:16,display:"flex",flexDirection:"column",gap:8,position:"relative"}}><div style={{position:"absolute",top:8,right:14,fontSize:32,color:p.ac,opacity:.12,lineHeight:1}}>"</div><T k="quote" s={{fontSize:12,color:p.tx,lineHeight:1.5}}>This product changed how we work. Highly recommend it.</T><div style={{display:"flex",alignItems:"center",gap:8,marginTop:"auto"}}><Img k="avatar" s={{width:24,height:24,borderRadius:999,background:p.ac+"25"}}/><T k="name" s={{fontSize:11,fontWeight:500,color:p.tx}}>Jane Doe</T></div></div>;
  }

  /* ---- CMD PALETTE ---- */
  if(type==="cmd-palette"){
    const items=[{icon:"⌂",label:"Go to Dashboard"},{icon:"⚙",label:"Settings"},{icon:"?",label:"Help center"},{icon:"↗",label:"Open docs"}];
    if(v===0)return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,boxShadow:`0 16px 48px ${p.tx}12`,overflow:"hidden",display:"flex",flexDirection:"column"}}><div style={{padding:"10px 14px",borderBottom:`1px solid ${p.bd}`,display:"flex",alignItems:"center",gap:8}}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke={p.mu} strokeWidth="2" opacity=".3"><circle cx="11" cy="11" r="8"/><path d="M21 21l-4.35-4.35"/></svg><T k="search" s={{fontSize:12,color:p.mu,opacity:.4}}>Type a command...</T></div><div style={{flex:1,padding:4}}>{items.map((it,i)=><div key={i} style={{padding:"8px 10px",borderRadius:8,display:"flex",alignItems:"center",gap:10,background:i===0?p.ac+"10":"transparent"}}><span style={{fontSize:13,opacity:.5}}>{it.icon}</span><T k={`c${i}`} s={{fontSize:12,color:i===0?p.ac:p.tx}}>{it.label}</T>{i===0&&<span style={{marginLeft:"auto",fontSize:9,color:p.mu,opacity:.3}}>Enter ↵</span>}</div>)}</div></div>;
    if(v===1)return <div style={{...b,background:p.card,borderRadius:12,border:`1px solid ${p.bd}`,boxShadow:`0 8px 32px ${p.tx}08`,overflow:"hidden",display:"flex",flexDirection:"column"}}><div style={{padding:"10px 14px",borderBottom:`1px solid ${p.bd}`}}><T k="search" s={{fontSize:12,color:p.mu,opacity:.4}}>Search...</T></div><div style={{flex:1,padding:2}}>{items.map((it,i)=><div key={i} style={{padding:"8px 12px",display:"flex",alignItems:"center",gap:10,background:i===0?p.su:"transparent"}}><T k={`c${i}`} s={{fontSize:12,color:p.tx}}>{it.label}</T></div>)}</div></div>;
    return <div style={{...b,background:p.card,borderRadius:14,border:`1px solid ${p.bd}`,boxShadow:`0 16px 48px ${p.tx}12`,overflow:"hidden",display:"flex",flexDirection:"column"}}><div style={{padding:"10px 14px",borderBottom:`1px solid ${p.bd}`}}><T k="search" s={{fontSize:12,color:p.mu,opacity:.4}}>Type a command...</T></div><div style={{padding:4}}><div style={{fontSize:9,color:p.mu,fontWeight:600,textTransform:"uppercase",letterSpacing:"0.08em",padding:"6px 10px 2px"}}>Navigation</div>{items.slice(0,2).map((it,i)=><div key={i} style={{padding:"8px 10px",borderRadius:8,display:"flex",alignItems:"center",gap:10,background:i===0?p.ac+"10":"transparent"}}><span style={{fontSize:13,opacity:.5}}>{it.icon}</span><T k={`c${i}`} s={{fontSize:12,color:p.tx}}>{it.label}</T></div>)}<div style={{fontSize:9,color:p.mu,fontWeight:600,textTransform:"uppercase",letterSpacing:"0.08em",padding:"6px 10px 2px"}}>Help</div>{items.slice(2).map((it,i)=><div key={i+2} style={{padding:"8px 10px",borderRadius:8,display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:13,opacity:.5}}>{it.icon}</span><T k={`c${i+2}`} s={{fontSize:12,color:p.tx}}>{it.label}</T></div>)}</div></div>;
  }

  /* ---- STEPPER ---- */
  if(type==="stepper"){
    const steps=["Account","Details","Confirm"];
    const active=1;
    if(v===0)return <div style={{...b,display:"flex",alignItems:"center",justifyContent:"space-between"}}>{steps.map((s,i)=><React.Fragment key={i}>{i>0&&<div style={{flex:1,height:2,background:i<=active?p.ac:p.bd,margin:"0 8px"}}/>}<div style={{display:"flex",alignItems:"center",gap:6}}><div style={{width:24,height:24,borderRadius:999,background:i<active?p.ac:i===active?p.ac+"20":"transparent",border:i>active?`1.5px solid ${p.bd}`:"none",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:10,color:i<active?"#fff":i===active?p.ac:p.mu,fontWeight:600}}>{i<active?"✓":i+1}</span></div><T k={`s${i}`} s={{fontSize:11,color:i<=active?p.tx:p.mu,fontWeight:i===active?500:400}}>{s}</T></div></React.Fragment>)}</div>;
    if(v===1)return <div style={{...b,display:"flex",flexDirection:"column",gap:0,justifyContent:"center"}}>{steps.map((s,i)=><div key={i} style={{display:"flex",gap:10}}><div style={{display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{width:20,height:20,borderRadius:999,background:i<=active?p.ac:p.su,border:i>active?`1.5px solid ${p.bd}`:"none",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:9,color:i<=active?"#fff":p.mu,fontWeight:600}}>{i<active?"✓":i+1}</span></div>{i<2&&<div style={{width:2,height:16,background:i<active?p.ac:p.bd}}/>}</div><T k={`s${i}`} s={{fontSize:11,color:i<=active?p.tx:p.mu,fontWeight:i===active?500:400,paddingTop:2}}>{s}</T></div>)}</div>;
    return <div style={{...b,display:"flex",alignItems:"center",justifyContent:"center",gap:12}}>{steps.map((s,i)=><React.Fragment key={i}>{i>0&&<div style={{width:20,height:1,background:p.bd}}/>}<div style={{width:10,height:10,borderRadius:999,background:i<=active?p.ac:p.bd}}/></React.Fragment>)}</div>;
  }

  /* ---- TIMELINE ---- */
  if(type==="timeline"){
    const events=[{title:"Project started",desc:"Initial setup complete"},{title:"Design review",desc:"Approved by team"},{title:"Launch",desc:"Coming soon"}];
    if(v===0)return <div style={{...b,display:"flex",flexDirection:"column",gap:0}}>{events.map((ev,i)=><div key={i} style={{display:"flex",gap:12,paddingBottom:i<2?16:0}}><div style={{display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{width:10,height:10,borderRadius:999,background:i===0?p.ac:p.su,border:`2px solid ${i===0?p.ac:p.bd}`,flexShrink:0}}/>{i<2&&<div style={{width:2,flex:1,background:p.bd}}/>}</div><div><T k={`t${i}`} s={{fontSize:12,fontWeight:500,color:p.tx}}>{ev.title}</T><T k={`d${i}`} s={{fontSize:10,color:p.mu,display:"block",marginTop:2}}>{ev.desc}</T></div></div>)}</div>;
    if(v===1)return <div style={{...b,display:"flex",flexDirection:"column",gap:0}}>{events.map((ev,i)=><div key={i} style={{display:"flex",gap:0,paddingBottom:i<2?12:0}}><div style={{flex:1,textAlign:"right",paddingRight:16}}>{i%2===0&&<><T k={`t${i}`} s={{fontSize:12,fontWeight:500,color:p.tx}}>{ev.title}</T><T k={`d${i}`} s={{fontSize:10,color:p.mu,display:"block"}}>{ev.desc}</T></>}</div><div style={{display:"flex",flexDirection:"column",alignItems:"center"}}><div style={{width:8,height:8,borderRadius:999,background:p.ac,flexShrink:0}}/>{i<2&&<div style={{width:1,flex:1,background:p.bd}}/>}</div><div style={{flex:1,paddingLeft:16}}>{i%2===1&&<><T k={`t${i}`} s={{fontSize:12,fontWeight:500,color:p.tx}}>{ev.title}</T><T k={`d${i}`} s={{fontSize:10,color:p.mu,display:"block"}}>{ev.desc}</T></>}</div></div>)}</div>;
    return <div style={{...b,display:"flex",flexDirection:"column",gap:12}}>{events.map((ev,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:6,height:6,borderRadius:999,background:i===0?p.ac:p.mu+"40",flexShrink:0}}/><T k={`t${i}`} s={{fontSize:12,color:i===0?p.tx:p.mu}}>{ev.title}</T></div>)}</div>;
  }

  return <div style={{...b,background:p.su,borderRadius:12}}/>;
}

function AnimStyle(){return <style>{ANIM_STYLE}</style>}

function CWithAnim(props){
  return <><AnimStyle/><C {...props}/></>;
}

export default CWithAnim;
