export const STORE_KEY = "tasteprint";

export const FONTS = [
  {name:"DM Sans",family:"'DM Sans',system-ui,sans-serif"},
  {name:"Inter",family:"'Inter',system-ui,sans-serif"},
  {name:"Plus Jakarta Sans",family:"'Plus Jakarta Sans',system-ui,sans-serif"},
  {name:"Manrope",family:"'Manrope',system-ui,sans-serif"},
  {name:"Space Grotesk",family:"'Space Grotesk',system-ui,sans-serif"},
  {name:"Outfit",family:"'Outfit',system-ui,sans-serif"},
  {name:"Sora",family:"'Sora',system-ui,sans-serif"},
  {name:"Work Sans",family:"'Work Sans',system-ui,sans-serif"},
  {name:"Figtree",family:"'Figtree',system-ui,sans-serif"},
  {name:"Instrument Serif",family:"'Instrument Serif',Georgia,serif"},
  {name:"Geist",family:"'Geist',system-ui,sans-serif"},
  {name:"JetBrains Mono",family:"'JetBrains Mono',monospace"},
  {name:"Playfair Display",family:"'Playfair Display',Georgia,serif"},
  {name:"Bricolage Grotesque",family:"'Bricolage Grotesque',system-ui,sans-serif"},
  {name:"General Sans",family:"'General Sans',system-ui,sans-serif"},
  {name:"Cabinet Grotesk",family:"'Cabinet Grotesk',system-ui,sans-serif"},
  {name:"Poppins",family:"'Poppins',system-ui,sans-serif"},
];

export const FONT_URL = "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Manrope:wght@400;500;600;700&family=Space+Grotesk:wght@400;500;600;700&family=Outfit:wght@400;500;600;700&family=Sora:wght@400;500;600;700&family=Work+Sans:wght@400;500;600;700&family=Figtree:wght@400;500;600;700&family=Instrument+Serif&family=Geist:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&family=Playfair+Display:wght@400;500;600;700&family=Bricolage+Grotesque:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap";

export const PAL = {
  warm:  { bg:"#FFF8F2",card:"#FFFFFF",ac:"#E07A5F",ac2:"#F2B880",tx:"#3D2C2C",mu:"#9C8578",bd:"rgba(224,122,95,0.12)",su:"#FDF0E8",name:"Warm" },
  cool:  { bg:"#F4F7FB",card:"#FFFFFF",ac:"#5B8DB8",ac2:"#7CAED4",tx:"#2C3644",mu:"#7A8B9C",bd:"rgba(91,141,184,0.12)",su:"#EBF2F8",name:"Cool" },
  earth: { bg:"#F7F4F0",card:"#FFFFFF",ac:"#8C7B6C",ac2:"#B8A08C",tx:"#3D3630",mu:"#A09488",bd:"rgba(140,123,108,0.12)",su:"#F0ECE6",name:"Earth" },
  noir:  { bg:"#1A1A1E",card:"#242428",ac:"#FFFFFF",ac2:"#888890",tx:"#F0F0F2",mu:"#78787E",bd:"rgba(255,255,255,0.08)",su:"#2A2A2E",name:"Noir" },
  candy: { bg:"#FFF5F9",card:"#FFFFFF",ac:"#E8589C",ac2:"#A864D4",tx:"#3A2434",mu:"#A88898",bd:"rgba(232,88,156,0.12)",su:"#FDE8F2",name:"Candy" },
  cloud: { bg:"#FAF8F5",card:"#FFFFFF",ac:"#B8A99A",ac2:"#D4C5B5",tx:"#3A3530",mu:"#A09890",bd:"rgba(184,169,154,0.12)",su:"#F4F0EB",name:"Cloud" },
  mono:  { bg:"#F5F5F5",card:"#FFFFFF",ac:"#555555",ac2:"#888888",tx:"#1A1A1A",mu:"#888888",bd:"rgba(0,0,0,0.08)",su:"#EEEEEE",name:"Mono" },
  neon:  { bg:"#0F1114",card:"#1A1D22",ac:"#39FF14",ac2:"#CCFF00",tx:"#E8E8E8",mu:"#6B7080",bd:"rgba(57,255,20,0.1)",su:"#161920",name:"Neon" },
  mint:  { bg:"#F2F8F6",card:"#FFFFFF",ac:"#3B9B7A",ac2:"#6BC4A6",tx:"#1E3A30",mu:"#7A9E90",bd:"rgba(59,155,122,0.12)",su:"#E8F4F0",name:"Mint" },
  mocha: { bg:"#F5F0EB",card:"#FFFFFF",ac:"#6F4E37",ac2:"#A0785C",tx:"#2C2018",mu:"#8C7A6B",bd:"rgba(111,78,55,0.12)",su:"#EDE6DF",name:"Mocha" },
  lavender:{ bg:"#F5F2FA",card:"#FFFFFF",ac:"#7C5CBF",ac2:"#A78BDA",tx:"#2A2040",mu:"#8A80A0",bd:"rgba(124,92,191,0.12)",su:"#ECE8F6",name:"Lavender" },
  ocean: { bg:"#F0F6FA",card:"#FFFFFF",ac:"#2B7A9E",ac2:"#5BAFCE",tx:"#1A3040",mu:"#6A8C9E",bd:"rgba(43,122,158,0.12)",su:"#E4F0F6",name:"Ocean" },
  forest:{ bg:"#F0F4F0",card:"#FFFFFF",ac:"#3D6B4E",ac2:"#6B9E7C",tx:"#1A2E20",mu:"#6A8B72",bd:"rgba(61,107,78,0.12)",su:"#E4EDE6",name:"Forest" },
};

export const VARIANTS = {
  button:    ["Filled","Outline","Ghost","Pill","Brutal","Glass","Terminal"],
  card:      ["Elevated","Outlined","Filled bg","Top media","Minimal","Glass","Brutal","Terminal"],
  "card-sm": ["Rounded","Horizontal","Tinted","Glass","Brutal"],
  hero:      ["Gradient","Centered","Bold fill","Terminal","Glass","Brutal"],
  navbar:    ["Classic","Underline","Pill","Glass","Terminal","Brutal","Gradient"],
  tabs:      ["Segmented","Underline","Pill chips","Glass","Bordered","Brutal","Gradient"],
  heading:   ["Clean","Accent bar","Overline","Gradient","Badge","Brutal","Gradient glow"],
  "stat-card":["Outlined","Tinted icon","Left accent","Inverted","Terminal","Brutal","Gradient"],
  "dash-panel":["Telemetry","Signal","Minimal","Gradient","Glass"],
  "image-placeholder":["Subtle","Gradient","Dashed","Glass","Brutal"],
  "avatar-row":["Circular","Small tight","Rounded sq","Glass","Gradient ring"],
  "list-item":["Card row","Divider","Tinted","Glass","Settings","Brutal","Gradient"],
  input:     ["Outlined","Labeled","Filled","Underline","Glass","Brutal","Gradient"],
  search:    ["Bordered","Pill kbd","Underline","Glass","AI","Brutal","Gradient"],
  toggle:    ["Round","Square","Labeled","iOS","Brutal","Glass"],
  badge:     ["Tinted","Solid","Outline","Glass","Brutal","Gradient","Counter"],
  toast:     ["Card","Dark snack","Accent bar","Glass","Brutal","Gradient"],
  progress:  ["Round","Flat","Thin","Striped","Glow","Brutal","Gradient"],
  modal:     ["Card","Minimal","Sheet","Glass","Destructive","Brutal","Gradient"],
  sidebar:   ["Full","Minimal","Grouped","Glass","Brutal","Gradient"],
  table:     ["Striped","Bordered","Minimal","Terminal","Glass","Gradient"],
  accordion: ["Bordered","Card","Minimal","Glass","Accent","Brutal","Gradient"],
  footer:    ["Columns","Simple","Dark","Branded","Glass","Brutal","Gradient"],
  "bento-grid":["Even","Featured","Mixed","Gradient","Glass"],
  dropdown:  ["Bordered","Minimal","Rounded","Glass","Grouped","Brutal","Gradient"],
  select:    ["Outlined","Pill","Underline","Glass","Grouped","Brutal","Gradient"],
  checkbox:  ["Square","Round","Toggle row","Card","Chip","Brutal","Gradient"],
  slider:    ["Round","Thin","Stepped","Gradient","Glass","Brutal","Gradient glow"],
  alert:     ["Tinted","Card","Banner","Glass","Brutal","Gradient"],
  pagination:["Numbered","Dots","Minimal","Pill","Glass","Brutal","Gradient"],
  "pricing-card":["Clean","Featured","Minimal","Gradient","Glass","Brutal","Gradient glow"],
  "product-card":["Standard","Sale badge","Horizontal","Wishlist","Glass","Brutal","Gradient"],
  "cart-item":["Standard","Compact","Detailed","Swipe","Brutal"],
  "feature-table":["Checkmark","Highlighted","Minimal","Gradient","Glass"],
  "promo-banner":["Gradient","Pill","Countdown","Glass","Social Proof"],
  "order-summary":["Card","Compact","Discount","Itemized","Glass"],
  rating:["Stars","Compact","Review","Sentiment","Breakdown","Brutal","Gradient"],
  receipt:["Dashed","Clean","Digital","Thermal","Glass"],
  "sub-toggle":["Cards","Switch","Pill","Glass","Brutal","Gradient"],
  tooltip:   ["Light","Dark","Arrow","Glass","Rich","Brutal","Gradient"],
  breadcrumb:["Slash","Arrow","Dots","Pill","Underline","Brutal","Gradient"],
  skeleton:  ["Card","List","Profile","Feed","Dashboard"],
  chart:     ["Bar","Line","Donut","Sparkline","Area"],
  testimonial:["Card","Minimal","Bubble","Glass","Hero","Brutal","Gradient"],
  "cmd-palette":["Full","Minimal","Grouped","Spotlight","Glass"],
  stepper:   ["Horizontal","Vertical","Dots","Pill","Icon","Brutal","Gradient"],
  timeline:  ["Left","Centered","Minimal","Card","Activity","Brutal","Gradient"],
  chat:      ["Bubble","Thread","Terminal","Glass","Gradient"],
  "media-player":["Minimal","Full","Terminal","Glass","Vinyl","Brutal","Gradient"],
  "profile-card":["Standard","Compact","Terminal","Glass","Gradient","Brutal","Gradient glow"],
  "code-block":["Dark","Light","Terminal","Live IDE","Typewriter","Diff","Notebook","Review","Minimap","ASCII Art","Benchmark"],
  notification:["List","Compact","Dot","Card","Glass","Brutal","Gradient"],
  "tag-input":["Rounded","Square","Outlined","Colorful","Input"],
  kanban:    ["Cards","Compact","Terminal","Gradient","Glass"],
};

export const LIB = [
  { cat:"Structure", items:[
    {type:"card",label:"Card",w:280,h:200},
    {type:"card-sm",label:"Small card",w:200,h:130},
    {type:"hero",label:"Hero",w:480,h:210},
    {type:"bento-grid",label:"Bento grid",w:340,h:220},
  ]},
  { cat:"Navigation", items:[
    {type:"navbar",label:"Nav bar",w:480,h:52},
    {type:"tabs",label:"Tabs",w:300,h:42},
    {type:"sidebar",label:"Sidebar",w:180,h:280},
    {type:"footer",label:"Footer",w:480,h:110},
  ]},
  { cat:"Content", items:[
    {type:"heading",label:"Heading",w:260,h:44},
    {type:"stat-card",label:"Stat card",w:160,h:110},
    {type:"image-placeholder",label:"Image",w:240,h:150},
    {type:"avatar-row",label:"Avatars",w:150,h:40},
    {type:"list-item",label:"List item",w:300,h:60},
    {type:"table",label:"Table",w:360,h:180},
    {type:"accordion",label:"Accordion",w:300,h:170},
  ]},
  { cat:"Input", items:[
    {type:"button",label:"Button",w:148,h:44},
    {type:"input",label:"Text input",w:248,h:44},
    {type:"search",label:"Search",w:270,h:44},
    {type:"toggle",label:"Toggle",w:48,h:28},
    {type:"dropdown",label:"Dropdown",w:200,h:150},
    {type:"select",label:"Select",w:220,h:40},
    {type:"checkbox",label:"Checkbox",w:180,h:90},
    {type:"slider",label:"Slider",w:200,h:28},
  ]},
  { cat:"Feedback", items:[
    {type:"badge",label:"Badge",w:72,h:28},
    {type:"toast",label:"Toast",w:290,h:56},
    {type:"progress",label:"Progress",w:220,h:8},
    {type:"alert",label:"Alert",w:300,h:56},
    {type:"pagination",label:"Pagination",w:220,h:36},
  ]},
  { cat:"Commerce", items:[
    {type:"pricing-card",label:"Pricing card",w:240,h:280},
    {type:"product-card",label:"Product card",w:220,h:260},
    {type:"cart-item",label:"Cart item",w:320,h:72},
    {type:"feature-table",label:"Feature table",w:400,h:200},
    {type:"promo-banner",label:"Promo banner",w:360,h:56},
    {type:"order-summary",label:"Order summary",w:260,h:200},
    {type:"rating",label:"Rating",w:220,h:60},
    {type:"receipt",label:"Receipt",w:240,h:220},
    {type:"sub-toggle",label:"Plan toggle",w:300,h:80},
  ]},
  { cat:"Data", items:[
    {type:"dash-panel",label:"Dashboard",w:280,h:180},
    {type:"chart",label:"Chart",w:260,h:180},
    {type:"testimonial",label:"Testimonial",w:280,h:140},
    {type:"skeleton",label:"Skeleton",w:260,h:120},
    {type:"kanban",label:"Kanban",w:360,h:220},
  ]},
  { cat:"Utility", items:[
    {type:"tooltip",label:"Tooltip",w:140,h:60},
    {type:"breadcrumb",label:"Breadcrumb",w:240,h:28},
    {type:"cmd-palette",label:"Cmd palette",w:300,h:200},
    {type:"stepper",label:"Stepper",w:280,h:44},
    {type:"timeline",label:"Timeline",w:240,h:200},
    {type:"tag-input",label:"Tags",w:260,h:36},
    {type:"code-block",label:"Code block",w:480,h:280},
  ]},
  { cat:"Overlay", items:[
    {type:"modal",label:"Modal",w:300,h:200},
    {type:"notification",label:"Notification",w:300,h:180},
  ]},
  { cat:"Social", items:[
    {type:"chat",label:"Chat",w:300,h:320},
    {type:"media-player",label:"Media player",w:300,h:120},
    {type:"profile-card",label:"Profile card",w:240,h:180},
  ]},
];

export const DEFAULT_PROPS = {
  toggle:        { on: true },
  checkbox:      { checked: [true, false, false] },
  tabs:          { active: 0 },
  navbar:        { active: 0 },
  sidebar:       { active: 0 },
  pagination:    { active: 2, total: 8 },
  stepper:       { active: 1 },
  timeline:      { active: 0 },
  accordion:     { open: [true, false, false] },
  dropdown:      { active: 0 },
  "cmd-palette": { active: 0 },
  progress:      { pct: 68 },
  slider:        { pct: 65 },
  "media-player":{ pct: 42, playing: true },
  testimonial:   { stars: 4 },
  rating:        { stars: 4 },
  "sub-toggle":  { active: 1 },
  "dash-panel":  { bars: [65,42,78,35,55,88,48], ring: 72 },
  chart:         { bars: [55,80,45,90,65,75], highlight: 3 },
  notification:  { read: [false, false, true] },
  alert:         { level: 0 },
  toast:         { level: 0 },
  "pricing-card":{ featured: false },
  "product-card":{ wishlisted: false },
  "profile-card":{ online: true },
  kanban:        { active: 1 },
  skeleton:      { loading: true },
  "bento-grid":  { active: 0 },
  "feature-table":{ highlight: 1 },
  "cart-item":   { qty: 1 },
  receipt:       { tip: 0 },
  "order-summary":{ discount: false },
  "promo-banner":{ dismissed: false },
  table:         { highlight: 0 },
  "stat-card":   { trend: 0 },
  "list-item":   { on: true },
  "avatar-row":  { active: 0 },
  "tag-input":   { active: 0 },
  "card-sm":     { featured: false },
  footer:        { active: 0 },
  hero:          { active: 0 },
  toggle:        { on: true },
  button:        { loading: false },
};

export const HAS_PROPS = new Set(Object.keys(DEFAULT_PROPS));

export const HAS_TEXT = new Set(["button","card","card-sm","hero","navbar","tabs","heading","stat-card","dash-panel","input","search","badge","toast","modal","sidebar","footer","accordion","table","list-item","dropdown","select","checkbox","alert","pagination","pricing-card","product-card","cart-item","feature-table","promo-banner","order-summary","rating","receipt","sub-toggle","tooltip","breadcrumb","testimonial","cmd-palette","stepper","timeline","bento-grid","chart","chat","media-player","profile-card","code-block","notification","tag-input","kanban"]);
